### ISSUE TITLE
Install failed: patch-package not installed

### ISSUE THREAD

**Issue by Hazmi35** [discordjs/opus#10]
**Please describe the problem you are having in as much detail as possible:** The title says it all

**Include a reproducible code sample here, if possible:**
```sh
$ npm install @discordjs/opus

> @discordjs/opus@0.2.0 install C:\Users\hzmi\Desktop\test\node_modules\@discordjs\opus
> patch-package && node-pre-gyp install --fallback-to-build

'patch-package' is not recognized as an internal or external command, operable program, or batch file.
```

**Further details:**
- @discordjs/opus version: v0.2.0
- Node.js Version: v12.16.2
- Operating system: Windows Build 19041.208 (Insider slow ring)
- The priority this issue should have – please be realistic and elaborate if possible: Critical?

**Comment by Naim2000** [comment]
Chances are you probably need to restart your command prompt.

**Comment by Hazmi35** [comment]
Nope, didn't work seems like npm didn't install devDependencies of @discordjs/opus, also tried on WSL still failing
