### ISSUE TITLE
Can't install the module.

### ISSUE THREAD

**Issue by XG-2580** [discordjs/opus#114]
Hello, I'm gonna to install @discordjs/opus on window and used node17.x.x it always error. So anything to solve this problem?

**Comment by iCrawl** [comment]
Yeah we don't support node.js 17 yet.

**Comment by XG-2580** [comment]
Ohh, I see

**Comment by MaxGamer637** [comment]
Thank you, I was in the same problem, and it solved. But I saw a developer that used _opus_ with  the node.js version >17, and it worked, idk why.

**Comment by NotNexuss** [comment]
I can't install discordjs/opus on replit too, any solutions?

**Comment by StephenL13** [comment]
I tried to use the legacy version of Node.js on Replit for my music bot since it has Python unlike the new one with Nix. Not sure why they didn't include Python on hand as it is the important core for audio playback
