### ISSUE TITLE
Can not install @discordjs/opus in build/local environment

### ISSUE THREAD

**Issue by riflowth** [discordjs/opus#133]
**Please describe the problem you are having in as much detail as possible:**

I cannot install `@discordjs/opus` on GitHub Action build environment
with the latest ubuntu and in my local machines MacOS / WIndow.
Build logs: https://github.com/riflowth/tier-discord-bot/runs/7052114942?check_suite_focus=true#step:6:268

### Notes
It can install the dependencies successfully before this day.
But today, it cannot install @discordjs/opus successfully
**without any changes of dependencies / lockfile / dockerfile / application code.**

<img width="300" alt="image" src="https://user-images.githubusercontent.com/17198802/175761408-80f3edbe-a1ae-4b55-9c43-f17957552ab8.png">

**Source code**: https://github.com/riflowth/tier-discord-bot/

---

- @discordjs/opus version: 0.7.0
- Node.js version: 16
- Operating system: Latest ubuntu on GitHub Action / MacOS Monterey 12.4 (M1 Pro) / Window 11

**Comment by banbanleelee** [comment]
Same issue here:
Was running in Windows PowerShell. My command was npm install @discordjs/opus.

**Comment by almeidx** [comment]
Have you tried following the instructions in your error logs?

@riflowth 
```
#12 18.73 gyp ERR! find Python **********************************************************
#12 18.73 gyp ERR! find Python You need to install the latest version of Python.
#12 18.73 gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
#12 18.73 gyp ERR! find Python you can try one of the following options:
#12 18.73 gyp ERR! find Python - Use the switch --python="/path/to/pythonexecutable"
#12 18.73 gyp ERR! find Python   (accepted by both node-gyp and npm)
#12 18.73 gyp ERR! find Python - Set the environment variable PYTHON
#12 18.73 gyp ERR! find Python - Set the npm configuration variable python:
#12 18.73 gyp ERR! find Python   npm config set python "/path/to/pythonexecutable"
#12 18.73 gyp ERR! find Python For more information consult the documentation at:
#12 18.73 gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
#12 18.73 gyp ERR! find Python **********************************************************
```
***
@banbanleelee 
```
npm ERR! gyp ERR! find VS **************************************************************
npm ERR! gyp ERR! find VS You need to install the latest version of Visual Studio
npm ERR! gyp ERR! find VS including the "Desktop development with C++" workload.
npm ERR! gyp ERR! find VS For more information consult the documentation at:
npm ERR! gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
npm ERR! gyp ERR! find VS **************************************************************
```

**Comment by banbanleelee** [comment]
@[almeidx](https://github.com/almeidx)

**Comment by bumbummen99** [comment]
For me it is trying to download `opus-v0.7.0-node-v93-napi-v3-linux-x64-glibc-2.35.tar.gz` but that fiile is not released. Instead, it should be downloading `opus-v0.7.0-node-v93-napi-v3-linux-x64-glibc-2.31.tar.gz` which does exist. 
As you can see glibc version is not the same.
Ubuntu 22.04 ships with 2.35 but 2.31 is required which is the version default on 20.04.

**Comment by iCrawl** [comment]
Nothing is required, but we can only supply pre-builds for so many different versions.
If we don’t provide one, its still possible to locally build it yourself just fine, which is the step after the download fails or it can’t find the specific file you requested.

**Comment by riflowth** [comment]
@iCrawl 
I have fixed the problem by this solution https://github.com/riflowth/tier-discord-bot/commit/51e1e1e656c477f27c369fad86717958e1da4c29
