### ISSUE TITLE
Add JSDoc to decode method

### ISSUE THREAD

**Issue by Kirdock** [discordjs/opus#136]
**Is your feature request related to a problem? Please describe.**
Yes and no. The problem was that I didn't know which format is returned after calling `OpusEncoder.decode(...)`.

**Describe the ideal solution**
Add to the JSDoc of the `decode` method that it returns `PCM s16le` (PCM signed 16-bit little endian)

**Comment by kyranet** [comment]
Can you open a PR doing the mentioned changes? Or do you prefer somebody else to do this instead?
