### ISSUE TITLE
Json decoder error 

### ISSUE THREAD

**Issue by Jboltle** [discordjs/opus#139]
**Please describe the problem you are having in as much detail as possible:**

**Include a reproducible code sample here, if possible:**

```js
// Place your code here
```

**Further details:**

- @discordjs/opus version:
- Node.js version:
- Operating system:
- Priority this issue should have – please be realistic and elaborate if possible:

**Comment by Jboltle** [comment]
It keeps returning that the phone number is invalid

**Comment by kyranet** [comment]
This is neither a JSON decoder error nor a library that can return such error. Please inspect your code more closely before opening an issue.

Furthermore, please do not ignore the template when making issues.
