### ISSUE TITLE
I can't download opus on djs 14

### ISSUE THREAD

**Issue by Mamadou2211** [discordjs/opus#140]
While downloading discordjs/opus i got a long error some people told me to download vs 2022 with c++ and python3 but I still got an error
Error link
https://sourceb.in/qi7wYHVPUq
**Further details:**

- @discordjs/opus version:
- Node.js version: 19
- Operating system: v19.3.0
- Priority this issue should have – please be realistic and elaborate if possible:

**Comment by dubfib** [comment]
Install [@discordjs/opus](https://npmjs.com/package/@discordjs/opus) at the latest version `0.9.0`
```shell
npm uninstall @discordjs/opus
npm install @discordjs/opus@0.9.0
```
Node `19` support came out in `0.9.0` and you are using [@discordjs/opus](https://npmjs.com/package/@discordjs/opus) version `0.8.0`.
