### ISSUE TITLE
dyld[53422]: missing symbol called on `decode`.

### ISSUE THREAD

**Issue by kevinvdburgt** [discordjs/opus#142]
**Please describe the problem you are having in as much detail as possible:**

When running the example below, the response of the `opusEncode.decode` results in:

```
dyld[53422]: missing symbol called
```

**Include a reproducible code sample here, if possible:**

```js
    const opusEncoder = new OpusEncoder(24000, 1);

    const buffer = Buffer.from(
      '6801d5d27eca5a47fe2178960578db08005a1825a94e36157732dba57877684d3be3f200bf22a762064c83394dbec25de57a63a56617cb1733bc40069e7aa902ee0ac77dae09ac033484fdb01514ce',
      'hex',
    );

    const payload = opusEncoder.decode(buffer);

    console.log(payload);
```

**Further details:**

- @discordjs/opus version: 0.9.0
- Node.js version: v18.12.1
- Operating system: MacOS Ventura 13.1 (M1 2020 Mac mini 16GB)

**Comment by maxckelly** [comment]
+1

**Comment by kevinvdburgt** [comment]
@maxckelly I haven't found a solution to this yet.

For the part of my project where I do need this package I spin up and old linux laptop with an x64 architecture.

**Comment by maxckelly** [comment]
For anyone experiencing this I followed this steps and it now works. https://gist.github.com/adrienjoly/e29a6e73fb7e701eefd80ff9bde9abeb

**Comment by JacobLinCool** [comment]
Hi @kevinvdburgt, [this PR (#150)](https://github.com/discordjs/opus/pull/150) should fix the problem on ARM macOS without x86 emulation.
