### ISSUE TITLE
Support for Node 20

### ISSUE THREAD

**Issue by ddemile** [discordjs/opus#156]
### Feature

Make this package support node 20

### Ideal solution or implementation

Add binaries for node 20

**Comment by Bugslogger** [comment]
are you saying that @discordjs/opus is not supported for node 20?
then if I switch to node 18 and install it then it should work right?

**Comment by ngregrichardson** [comment]
In theory I should have looked at the issues on this repo before going down the rabbit hole, but the fact that there is also a maximum Node requirement should be mentioned in the README if possible. It would save quite a bit of time. Thanks!!

**Comment by vladfrangu** [comment]
The project is always buildable locally, even if we don't provide prebuilds. You just need to have build tools installed on your side. If you still cannot build the project even after that, follow up here
