### ISSUE TITLE
@discordjs/opus failing a build on Heroku

### ISSUE THREAD

**Issue by Arniox** [discordjs/opus#19]
**Please describe the problem you are having in as much detail as possible:**
Tried to install @discordjs/opus to use audio streaming and etc and it's failing on a heroku build

**Include a reproducible code sample here, if possible:**
```
-----> Node.js app detected
       
-----> Creating runtime environment
       
       NPM_CONFIG_LOGLEVEL=error
       NODE_ENV=production
       NODE_MODULES_CACHE=true
       NODE_VERBOSE=false
       
-----> Installing binaries
       engines.node (package.json):  unspecified
       engines.npm (package.json):   unspecified (use default)
       
       Resolving node version 12.x...
       Downloading and installing node 12.16.3...
       Using default npm version: 6.14.4
       
-----> Restoring cache
       - node_modules is checked into source control and cannot be cached
       
-----> Installing dependencies
       Prebuild detected (node_modules already exists)
       Rebuilding any native modules
       
       > @discordjs/opus@0.3.2 install /tmp/build_aa8678beaa8c32032607c57e2e8726d8/node_modules/@discordjs/opus
       > node-pre-gyp install --fallback-to-build
       
       sh: 1: node-pre-gyp: Permission denied
       npm ERR! code ELIFECYCLE
       npm ERR! errno 126
       npm ERR! @discordjs/opus@0.3.2 install: `node-pre-gyp install --fallback-to-build`
       npm ERR! Exit status 126
       npm ERR! 
       npm ERR! Failed at the @discordjs/opus@0.3.2 install script.
       npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
       
       npm ERR! A complete log of this run can be found in:
       npm ERR!     /tmp/npmcache.TkBdt/_logs/2020-05-07T13_44_09_511Z-debug.log
-----> Build failed
       
       We're sorry this build is failing! You can troubleshoot common issues here:
       https://devcenter.heroku.com/articles/troubleshooting-node-deploys
       
       Some possible problems:
       
       - node_modules checked into source control
         https://blog.heroku.com/node-habits-2016#9-only-git-the-important-bits
       
       - Node version not specified in package.json
         https://devcenter.heroku.com/articles/nodejs-support#specifying-a-node-js-version
       
       Love,
       Heroku
       
 !     Push rejected, failed to compile Node.js app.
 !     Push failed
```

**Further details:**

- @discordjs/opus version: 0.3.2
- Node.js version: 12.16.3
- Operating system: Windows 10
- Priority this issue should have – please be realistic and elaborate if possible: Low. This is a personal application so no stress to rush.

**Comment by iCrawl** [comment]
Yeah, Heroku is not advised to use with a music bot anyway.

Use `opusscript` if you *really* need it. Still not advised.

**Comment by Arniox** [comment]
> Yeah, Heroku is not advised to use with a music bot anyway.
> 
> Use `opusscript` if you _really_ need it. Still not advised.

Wait, so this issue has nothing to do with anything on my end? It's entirely Heroku?

**Comment by iCrawl** [comment]
Yup

**Comment by idislikebrian** [comment]
`opusscript `seems to have worked for me -- is the actual solution just not hosting app on Heroku?

**Comment by iCrawl** [comment]
Yes.

**Comment by OrionNetworkMCS** [comment]
So, If Your Still Having Issues I Recommend Using AWS's Free Tier EC2 Instances, They allow you to use Sudo, apt, and other package installers to install via an ssh from your local computer, they also have a built in method to connect to the shell instance on their website. However either way AWS is better and faster, and unlike Heroku will run a whole year with no hour limits at noticeably higher speeds. The downsides being you may have to start paying money to continue, as the trial is 1 year, or create a new account every year *which in my opinion isnt too bad*.
