### ISSUE TITLE
Linux install 404

### ISSUE THREAD

**Issue by RossmacD** [discordjs/opus#2]
When running `npm install @discordjs/opus` on linux it throws up a 404 error

```
node-pre-gyp WARN Using needle for node-pre-gyp https download 
node-pre-gyp WARN Tried to download(404): https://github.com/discordjs/opus/releases/download/v0.1.0/opus-v0.1.0-node-v64-linux-x64.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for @discordjs/opus@0.1.0 and node@10.15.3 (node-v64 ABI, glibc) (falling back to source compile with node-gyp) 
```

![image](https://user-images.githubusercontent.com/42966821/77776882-9818b880-7046-11ea-9404-7a38b6a5dd22.png)

Looking at the releases the URL should most likely be opus-v0.1.0-node-v72-linux-x64.tar.gz
I dont really know enough about node packages to know why this is happening but I assume its a publishing issue?

**Comment by iCrawl** [comment]
No, we don't build releases for node 10. It does fallback to building it locally on your system which is intended in this case.

**Comment by RossmacD** [comment]
Ahhh I see my bad sorry, thanks for the help!
