### ISSUE TITLE
Not able to encode wav file

### ISSUE THREAD

**Issue by RichardChaumont** [discordjs/opus#26]
I am trying to convert a WAV file using Node's `fs.readFile` and passing that buffer to `encoder.encode`. I get neither the result or a error thrown with a explanation of what is wrong. This is basically the example you have in the docs... right?

Bug? By design? or me missing something?

Online example: https://codesandbox.io/s/funny-jones-d7sls?file=/src/index.js

```js
const audioBuffer = await fs
    .readFile(file)
    .catch(err => console.log("Error reading input file:", err));

  console.log("LENGTH:", audioBuffer.length); // all good so far...
  const encoder = new OpusEncoder(41000, 2);

  let encoded = null;
  try {
    console.log("Trying to encode..."); // log runs
    encoded = encoder.encode(audioBuffer);
    console.log("Encoded!"); // log doesn't run :(
  } catch (err) {
    console.log("Encoding failed:", err); // no error thrown... :'(
  }
  return encoded;
```

**Further details:**

- @discordjs/opus version: `^0.3.2`
- Node.js version: `v14.2.0`
- Operating system: `Mac Mojave (10.14.6)`

**Comment by xnorpx** [comment]
Opus needs PCM input so you need to parse the wav header and initialize Opus with correct format then feed PCM to the encoder. 

https://en.wikipedia.org/wiki/WAV
https://en.wikipedia.org/wiki/Pulse-code_modulation

**Comment by RichardChaumont** [comment]
Hej! @xnorpx, thanks for checking this out!
Do you know of any Node project that does this? Or should it be added to the repo maybe? 🤔 

If you can give me pointers on how the code for it should look like would be great. Meanwhile will read the articles you pointed to 👍

**Comment by xnorpx** [comment]
sorry I am not so familiar with node, if it's just for testing you can use audacity to export wav files to raw. Then use the rawfile to encode decode. Then import into audacity again.

I am sure there is some wav libraries in node that you could use to just open and parse the header.

**Comment by Elipzer** [comment]
I get the same problem when loading from a pcm file that I converted with ffmpeg.

**Comment by xnorpx** [comment]
Here is a gist example https://gist.github.com/xnorpx/c5d12bb0211731980138c7fe33772f0e
