### ISSUE TITLE
@discordjs/opus. Error: package.json does not exist at ....

### ISSUE THREAD

**Issue by hemallc** [discordjs/opus#27]

**Comment by iCrawl** [comment]
Are you using https://github.com/electron-userland/electron-builder?

Generally speaking this package obviously has no support for webpack at all and never will, because native packages just can't.

**Comment by hemallc** [comment]
> Are you using https://github.com/electron-userland/electron-builder?
> 
> Generally speaking this package obviously has no support for webpack at all and never will, because native packages just can't.
Yes I am using Electron-builder.
May you recommend a solution for using @discordjs/opus in Electron project ?

Thank you so much ~~~
