### ISSUE TITLE
No Audio Output on Windows Server

### ISSUE THREAD

**Issue by UnbreakCode** [discordjs/opus#29]
**Please describe the problem you are having in as much detail as possible:**
Using OS: Windows Server 2012 R2, I'm trying to stream a .mp3 streamlink via DiscordJS over my Bot. I am not getting any audio output. I've tested my code on 2 other Windows machines and it worked. I installed VS Community 2019 on my Server with the Desktop Development with C++ Workload.
**Include a reproducible code sample here, if possible:**
const dispatcher = connection.play(`${streamLink}`)
```js
**Further details:**

- @discordjs/opus version: @discordjs/opus@0.3.2
- Node.js version: 12.18.2
- Operating system: Windows Server 2012 R2

**Comment by harqu** [comment]
I have the same problem

**Comment by flawnn** [comment]
I have the same issue

**Comment by thatrelevantperson** [comment]
Same issue, AWS EC2 Windows Server 2019
**DiscordJS V12** on NodeJS v12.

**Comment by Kiddo9000** [comment]
This seems to be a bug with `0.4.0`
Had the same issue. Updating Opus to `0.5.0` fixed the issue.

**Comment by UnbreakCode** [comment]
> This seems to be a bug with `0.4.0` and older
> Had the same issue. Updating Opus to `0.5.0` fixed the issue.

Yes it's working with the latest version
