### ISSUE TITLE
The system cannot find the path specified.

### ISSUE THREAD

**Issue by vampymaria** [discordjs/opus#31]
**Please describe the problem you are having in as much detail as possible:**
trying to install opus
**Include a reproducible code sample here, if possible:**
$ npm install --build-from-source

```js

> @discordjs/opus@0.3.2 install C:\Users\vampy\Documents\GitHub\Cookie\node_modules\@discordjs\opus
> node-pre-gyp install --fallback-to-build

The system cannot find the path specified.

npm ERR! code ELIFECYCLE
npm ERR! errno 3
npm ERR! @discordjs/opus@0.3.2 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 3
npm ERR!
npm ERR! Failed at the @discordjs/opus@0.3.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\vampy\AppData\Roaming\npm-cache\_logs\2020-07-26T16_43_30_239Z-debug.log
```

**Further details:**

- @discordjs/opus version:0.3.2
- Node.js version:14.6.0
- Operating system:Windows 10
- Priority this issue should have – please be realistic and elaborate if possible: Well ... Idk. But my discord bot cannot run without opus right now

**Comment by Ayfri** [comment]
Send the logs

**Comment by vampymaria** [comment]
[2020-07-26T16_43_30_239Z-debug.log](https://github.com/discordjs/opus/files/4978599/2020-07-26T16_43_30_239Z-debug.log)

**Comment by vampymaria** [comment]
I figured it out ...
