### ISSUE TITLE
encode() is not working

### ISSUE THREAD

**Issue by jreich888** [discordjs/opus#33]
I cannot get encode to work.  On a RPi4 the node environment will crash; on Windows the encode just prints Unknown Failure.  Decode is working for me on both platforms.  Even running with a static buffer, it fails.

```
var buffer = Buffer.alloc(8000,0);
const { OpusEncoder } = require('@discordjs/opus');

// Create the encoder.
// Specify 48kHz sampling rate and 2 channel size.
const encoder = new OpusEncoder(48000, 2);

// Encode and decode.
const encoded = encoder.encode(buffer);
const decoded = encoder.decode(encoded);
```

When I run on RPi4:
```
> const encoded = encoder.encode(buffer);
FATAL ERROR: Error::New napi_get_last_error_info
Aborted
```

On Windows:
```
> const encoded = encoder.encode(buffer);
Error: Unknown failure
```

Also tried the slightly larger test code in at `https://gist.github.com/xnorpx/c5d12bb0211731980138c7fe33772f0e`, same behavior.

I'd appreciate any insight or advice you could provide; I'm not that experience with testing or developing with native code in Node.

thanks.

**Further details:**

- @discordjs/opus version: 0.3.2
- Node.js version: v10.21.0 (RPi), v10.15.3 (Windows)
- Operating system:  Raspbian Buster, Windows 10 x64
- Priority this issue should have – please be realistic and elaborate if possible:

**Comment by jreich888** [comment]
I've done some further digging and testing, and have learned that there are rigid requirements for frame lengths, so you can't throw just any input buffer length and expect it to work.  So if you I changed the allocated buffer size to something like 3840 (20ms of 48khz stereo samples), it works.

This wasn't helped by the fact that the "encode" method doesn't check for errors and turn them into strings, like the decode() method does.    And when I went back to the xnorpx test code, I think that was failing because my test wav file was 44100 (unsupported sample rate).  The rest I'll chalk up to my own learning curve on the opus codec.

But the library's working now, thanks!

**Comment by iCrawl** [comment]
This is by design of this library.

If you look at the code and the library methods, it just wraps the native opus methods to expose them to node, no further validation or verification is done.
