### ISSUE TITLE
 Install issues

### ISSUE THREAD

**Issue by Asgarrrr** [discordjs/opus#34]
**Please describe the problem you are having in as much detail as possible:**
— This package fails to install via npm

![](https://i.imgur.com/n2UBOKo.png)

**Further details:**

https://pastebin.com/raw/49uQSLjL

- @discordjs/opus version:
- Node.js version: v12.17.0
- Operating system: macOS Catalina (c10.15.6)

**Comment by iCrawl** [comment]
This looks like an issue with your npm cache, and if it doesn't it's not an error with this library:

https://stackoverflow.com/a/52249619/13197036
