### ISSUE TITLE
Online linux host cannot install discordjs/opus

### ISSUE THREAD

**Issue by TechnoTew** [discordjs/opus#36]
**Please describe the problem you are having in as much detail as possible:**
Cannot install discordjs/opus when pushing the code to a online hosting system.

``` node-pre-gyp WARN Tried to download(404): https://github.com/discordjs/opus/releases/download/v0.3.2/opus-v0.3.2-node-v72-napi-v3-linux-x64-glibc-2.28.tar.gz ```

**Include a reproducible code sample here, if possible:**

```js
// Place your code here
```

**Further details:**

- @discordjs/opus version:
- Node.js version: v12.16.2
- Operating system: Linux
- Priority this issue should have – please be realistic and elaborate if possible:

**Comment by iCrawl** [comment]
https://github.com/discordjs/opus/issues/23#issuecomment-634734580
