### ISSUE TITLE
Not able to download a packages on termux nodejs lts

### ISSUE THREAD

**Issue by VlaDexa** [discordjs/opus#41]
Error: > @discordjs/opus@0.3.2 install /data/data/com.termux/files/home/node_modules/@discordjs/opus
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp WARN Tried to download(404): https://github.com/discordjs/opus/releases/download/v0.3.2/opus-v0.3.2-node-v72-napi-v3-android-arm64-unknown-unknown.tar.gz
node-pre-gyp WARN Pre-built binaries not found for @discordjs/opus@0.3.2 and node@12.18.3 (node-v72 ABI, unknown) (falling back to source compile with node-gyp)
make: Entering directory '/data/data/com.termux/files/home/node_modules/@discordjs/opus/build'
  CC(target) Release/obj.target/libopus/deps/opus/src/opus_multistream.o
warning: unknown warning option
      '-Wno-maybe-uninitialized'; did you mean
      '-Wno-uninitialized'? [-Wunknown-warning-option]
../deps/opus/src/opus_multistream.c:29:10: fatal error:
      'config.h' file not found
#include "config.h"
         ^~~~~~~~~~
1 warning and 1 error generated.
make: *** [deps/libopus.target.mk:300: Release/obj.target/libopus/deps/opus/src/opus_multistream.o] Error 1
make: Leaving directory '/data/data/com.termux/files/home/node_modules/@discordjs/opus/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 4.14.62-19164009
gyp ERR! command "/data/data/com.termux/files/usr/bin/node" "/data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/data/data/com.termux/files/home/node_modules/@discordjs/opus/prebuild/node-v72-napi-v3-android-arm64-unknown-unknown/opus.node" "--module_name=opus" "--module_path=/data/data/com.termux/files/home/node_modules/@discordjs/opus/prebuild/node-v72-napi-v3-android-arm64-unknown-unknown" "--napi_version=6" "--node_abi_napi=napi" "--napi_build_version=3" "--node_napi_label=napi-v3"
gyp ERR! cwd /data/data/com.termux/files/home/node_modules/@discordjs/opus
gyp ERR! node -v v12.18.3
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/data/data/com.termux/files/usr/bin/node /data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/data/data/com.termux/files/home/node_modules/@discordjs/opus/prebuild/node-v72-napi-v3-android-arm64-unknown-unknown/opus.node --module_name=opus --module_path=/data/data/com.termux/files/home/node_modules/@discordjs/opus/prebuild/node-v72-napi-v3-android-arm64-unknown-unknown --napi_version=6 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/data/data/com.termux/files/home/node_modules/@discordjs/opus/node_modules/@discordjs/node-pre-gyp/lib/util/compile.js:72:20)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
node-pre-gyp ERR! System Linux 4.14.62-19164009
node-pre-gyp ERR! command "/data/data/com.termux/files/usr/bin/node" "/data/data/com.termux/files/home/node_modules/@discordjs/opus/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /data/data/com.termux/files/home/node_modules/@discordjs/opus
node-pre-gyp ERR! node -v v12.18.3
node-pre-gyp ERR! node-pre-gyp -v v0.1.0
node-pre-gyp ERR! not ok
Failed to execute '/data/data/com.termux/files/usr/bin/node /data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/data/data/com.termux/files/home/node_modules/@discordjs/opus/prebuild/node-v72-napi-v3-android-arm64-unknown-unknown/opus.node --module_name=opus --module_path=/data/data/com.termux/files/home/node_modules/@discordjs/opus/prebuild/node-v72-napi-v3-android-arm64-unknown-unknown --napi_version=6 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3' (1)
npm WARN enoent ENOENT: no such file or directory, open '/data/data/com.termux/files/home/package.json'
npm WARN home No description
npm WARN home No repository field.
npm WARN home No README data
npm WARN home No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @discordjs/opus@0.3.2 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @discordjs/opus@0.3.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /data/data/com.termux/files/home/.npm/_logs/2020-09-30T19_05_57_035Z-debug.log

**Comment by TisRyno** [comment]
I get exactly the same issue running on Node 14.12, only happened since I upgraded from Ubuntu 18 to Ubuntu 20.

**Comment by taksumaki** [comment]
Also with the same problem in ubuntu 20, it helps

**Comment by davipatricio** [comment]
Can repro.

**Comment by KrisTheNewest** [comment]
Same goes for Debian 9.13, Node v12.19.0 and  npm 6.14.8

**Comment by VlaDexa** [comment]
So, from reading those error logs it seems that node can't find some files in github, then tries to compile opus, but fails when the program can't find the file config.h. From trying to compile opus, I know that it requiers to launch some binary to make a config file. So devs need to include a comand that starts the configure binary

**Comment by TisRyno** [comment]
I actually fixed this for my Ubuntu 20 issue, turns out when I upgraded I lost g++

Fix for me was:

`sudo apt install g++`

Hope this helps some people

**Comment by iCrawl** [comment]
I don't think I will add any specific support for termux in the future.
So not a bug.

**Comment by LeapofAzzam-backup** [comment]
> I don't think I will add any specific support for termux in the future.
> So not a bug.

Fuck you, you must add termux support, also merge #55
