### ISSUE TITLE
Can't install discord opus on Ubuntu

### ISSUE THREAD

**Issue by Sardonyx78** [discordjs/opus#45]
**Please describe the problem you are having in as much detail as possible:**
I cant install discordjs opus, I have python, gcc, make and node gyp
**Include a reproducible code sample here, if possible:**
Running this line on a project whose djs opus as dependency:
`npm i -D`
```
sardonyx@keyubu:~/bot$ npm i -D
npm ERR! code 127
npm ERR! path /home/sardonyx/bot/node_modules/@discordjs/opus
npm ERR! command failed
npm ERR! command sh -c node-pre-gyp install --fallback-to-build
npm ERR! sh: 1: node-pre-gyp: not found

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/sardonyx/.npm/_logs/2020-11-09T13_20_22_488Z-debug.log
```
Error Log: https://hastebin.com/kuyevayata.apache

**Further details:**

- @discordjs/opus version: 0.3.3
- Node.js version: v15.1.0
- Operating system: Ubuntu 18.04
- Priority this issue should have – please be realistic and elaborate if possible: Low

**Comment by iCrawl** [comment]
`npm i -D`, the `-D` here, whats that even supposed to do?

Additionally, theres too little info. A repo or package.json to reproduce would be kinda nice.

**Comment by Sardonyx78** [comment]
package.json:
```json
{
  "name": "bot",
  "version": "1.0.0",
  "description": "",
  "main": "dist/index.js",
  "author": "Sardonyx78 <sardonyx@sardonyx.me>",
  "license": "MIT",
  "devDependencies": {
    "@types/node": "^14.10.1",
    "@types/redis": "^2.8.27",
    "@types/mathjs": "^6.0.5",
    "@types/mongoose": "^5.7.36"
  },
  "dependencies": {
    "@discordjs/opus": "^0.3.3",
    "canvas": "^2.6.1",
    "discord.js": "^12.3.1",
    "mathjs": "^7.2.0",
    "moment": "^2.28.0",
    "mongoose": "^5.10.5",
    "redis": "^3.0.2",
    "source-server-query": "^1.0.1",
    "svg-captcha": "^1.4.0",
    "svg2img": "^0.8.1",
    "tslib": "^2.0.1"
  }
}
```

> `npm i -D`, the `-D` here, whats that even supposed to do?
Before you said that I thought we needed to put `-D` to install dev dependencies too. After a little research turns out that it was false.

**Comment by Sardonyx78** [comment]
btw using lts version of node fixes this error
