### ISSUE TITLE
cant install discord.js @discordjs/opus

### ISSUE THREAD

**Issue by Hoshiiiii** [discordjs/opus#47]
**Please describe the problem you are having in as much detail as possible:**
when doing npm install discord.js @discordjs/opus i am getting the node-pre-gyp is not recognized as a command error.
i already installed node-pre-gyp with npm but still getting the same issue. i deleted python 3 and downloaded python 2.7 too since im using v15 of node i guess.
**Include a reproducible code sample here, if possible:**
npm install discord.js @discordjs/opus

```js
// Place your code here
```

**Further details:**

- @discordjs/opus version: none cause it doesnt install

- Node.js version: v15.3.0 / Already tried v14.5.1 but same thats why i tried v15
- Operating system: Windows 10 Pro 64 bit
- Priority this issue should have – please be realistic and elaborate if possible:

[2020-12-02T04_21_35_255Z-debug.log](https://github.com/discordjs/opus/files/5626946/2020-12-02T04_21_35_255Z-debug.log)

**Comment by Hoshiiiii** [comment]
ok somehow i think my node installation got rekt. I clean installed windows 10 and its all good now

**Comment by LeYoshi05** [comment]
Same problem with my Win10 Home installation...

Here's the error code
[error.txt](https://github.com/discordjs/opus/files/5760074/error.txt)
[2021-01-02T09_44_54_029Z-debug.log](https://github.com/discordjs/opus/files/5760075/2021-01-02T09_44_54_029Z-debug.log)
