### ISSUE TITLE
Error: FATAL ERROR: Error::ThrowAsJavaScriptException napi_throw #5081

### ISSUE THREAD

**Issue by Scraayp** [discordjs/opus#49]
**Please describe the problem you are having in as much detail as possible:**
I get error when trying to play music, it looks like its the problem with discord.js opus

**Further details:**

- @discordjs/opus version: 12.5.1
- Node.js version: >12, not sure which one because am using hosting!
- Operating system: Linux
- Priority this issue should have – please be realistic and elaborate if possible: It's not that required right now, but would be great if got fast response

```
FATAL ERROR: Error::ThrowAsJavaScriptException napi_throw
1: 0xa17c40 node::Abort() [/usr/local/bin/node]
2: 0xa1804c node::OnFatalError(char const*, char const*) [/usr/local/bin/node]
3: 0xa180e9 [/usr/local/bin/node]
4: 0x9ebbfb napi_fatal_error [/usr/local/bin/node]
5: 0x7f62802e74b6 [/home/container/node_modules/@discordjs/opus/prebuild/node-v72-napi-v3-linux-x64-glibc-2.28/opus.node]
6: 0x7f62802e79eb Napi::Error::ThrowAsJavaScriptException() const [/home/container/node_modules/@discordjs/opus/prebuild/node-v72-napi-v3-linux-x64-glibc-2.28/opus.node]
7: 0x7f62802f20d8 OpusEncoder::Decode(Napi::CallbackInfo const&) [/home/container/node_modules/@discordjs/opus/prebuild/node-v72-napi-v3-linux-x64-glibc-2.28/opus.node]
8: 0x7f62802e9f47 Napi::InstanceWrap<OpusEncoder>::InstanceMethodCallbackWrapper(napi_env__*, napi_callback_info__*) [/home/container/node_modules/@discordjs/opus/prebuild/node-v72-napi-v3-linux-x64-glibc-2.28/opus.node]
9: 0x9cfc55 [/usr/local/bin/node]
10: 0xc019e9 [/usr/local/bin/node]
11: 0xc037d7 v8::internal::Builtin_HandleApiCall(int, unsigned long*, v8::internal::Isolate*) [/usr/local/bin/node]
12: 0x1409319 [/usr/local/bin/node]
/entrypoint.sh: line 12: 3013 Aborted (core dumped) /usr/local/bin/node /home/container/${BOT_JS_FILE} 
```

**Comment by iCrawl** [comment]
I don't really know how to reproduce this.

What type of hosting is this?

**Comment by Scraayp** [comment]
What do you mean by type???
It's a discord bot hosting using docker.

**Comment by Scraayp** [comment]
I found out the issue was that I was using node js v12! 

If you encounter this issue, try upgrading your node.js version to v13/14!

**Comment by CatDevz** [comment]
Reopening this issue as its occuring on Node version 15.5.0 for me aswell.

**System Details**
OS: Arch Linux x86_64 
KERNEL: 5.9.11-arch2-1 
CPU: Intel i5-8300H (8) @ 4.000GHz
GPU: NVIDIA GeForce GTX 1060 Mobile 6GB 

**Stacktrace**
```
FATAL ERROR: Error::ThrowAsJavaScriptException napi_throw
 1: 0x557a8e8fa1c1 node::Abort() [node]
 2: 0x557a8e81d13a node::FatalError(char const*, char const*) [node]
 3: 0x557a8e81d143  [node]
 4: 0x557a8e8c635b napi_fatal_error [node]
 5: 0x7fde841506aa  [/home/[REDACTED]/node_modules/@discordjs/opus/prebuild/node-v88-napi-v3-linux-x64-glibc-2.32/opus.node]
 6: 0x7fde84150dfc Napi::Error::ThrowAsJavaScriptException() const [/home/[REDACTED]/node_modules/@discordjs/opus/prebuild/node-v88-napi-v3-linux-x64-glibc-2.32/opus.node]
 7: 0x7fde8415cc68 OpusEncoder::Decode(Napi::CallbackInfo const&) [/home/[REDACTED]/node_modules/@discordjs/opus/prebuild/node-v88-napi-v3-linux-x64-glibc-2.32/opus.node]
 8: 0x7fde841543a7 Napi::InstanceWrap<OpusEncoder>::InstanceMethodCallbackWrapper(napi_env__*, napi_callback_info__*) [/home/[REDACTED]/node_modules/@discordjs/opus/prebuild/node-v88-napi-v3-linux-x64-glibc-2.32/opus.node]
 9: 0x557a8e8a6db5  [node]
10: 0x557a8eb37247 v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo) [node]
11: 0x557a8eb3802e  [node]
12: 0x557a8eb38522  [node]
13: 0x557a8eb387d6 v8::internal::Builtin_HandleApiCall(int, unsigned long*, v8::internal::Isolate*) [node]
14: 0x557a8f305439  [node]
```

**Comment by Roguyt** [comment]
I reported the issue earlier in the discord.js repository https://github.com/discordjs/discord.js/issues/5036
Node version doesn't seems to fix the issue, and it seems to appears randomly, where as soon as a bot crash and is replaced by another one (restarted automatically) it just keeps crashing.

**Comment by anhnhoktvn** [comment]
I have the same error. Any solution?

**Comment by OnkelTem** [comment]
Having the same issue.

```js
const { OpusEncoder } = require('@discordjs/opus');
const fs = require('fs');

// Create the encoder.
// Specify 48kHz sampling rate and 2 channel size.
const encoder = new OpusEncoder(48000, 2);

const encoded = fs.readFileSync('../32k.opus');

const decoded = encoder.decode(encoded);

console.log(decoded);
```

What I do wrong?

**Comment by JMTK** [comment]
Reproducible by using a non-opus stream and setting the type to `opus` (I know this seems counterintuitive, but I only discovered my stream wasn't properly opus until after).

An example of this occuring is when I was trying to use it with the `soundcloud-downloader` module:

```js
//assume voiceConnection is defined and joinedgg
let scdl = require('soundcloud-downloader').default;
let stream = await scdl.downloadFormat(song, "audio/ogg; codecs=\"opus\"");
voiceConnection.play(stream, {type: 'opus'});
```

Now I haven't debugged why this is causing this error since it's allegedly an opus stream, but this is the output once it hits the `play` line:
```
FATAL ERROR: Error::ThrowAsJavaScriptException napi_throw
 1: 0xa73180 node::Abort() [node]
 2: 0x99fc4d node::FatalError(char const*, char const*) [node]
 3: 0x99fc56  [node]
 4: 0xa3e1ab napi_fatal_error [node]
 5: 0x7fc72c4dac8e  [/app/node_modules/@discordjs/opus/prebuild/node-v88-napi-v3-linux-x64-glibc-2.31/opus.node]
 6: 0x7fc72c4db3ec Napi::Error::ThrowAsJavaScriptException() const [/app/node_modules/@discordjs/opus/prebuild/node-v88-napi-v3-linux-x64-glibc-2.31/opus.node]
 7: 0x7fc72c4e7d88 OpusEncoder::Decode(Napi::CallbackInfo const&) [/app/node_modules/@discordjs/opus/prebuild/node-v88-napi-v3-linux-x64-glibc-2.31/opus.node]
 8: 0x7fc72c4de2da Napi::InstanceWrap<OpusEncoder>::InstanceMethodCallbackWrapper(napi_env__*, napi_callback_info__*) [/app/node_modules/@discordjs/opus/prebuild/node-v88-napi-v3-linux-x64-glibc-2.31/opus.node]
 9: 0xa2147f  [node]
10: 0xcc0c4b  [node]
11: 0xcc21fc  [node]
12: 0xcc2876 v8::internal::Builtin_HandleApiCall(int, unsigned long*, v8::internal::Isolate*) [node]
13: 0x14e1d79  [node]
```
Despite having exception handlers in my code, my program forcibly exits and I don't seem to be able to catch it.

**Comment by stevenruidigao** [comment]
I am having this problem as well (with node 14.16.0).

**Comment by iCrawl** [comment]
Yes, this is a very thin wrapper around native opus. There will be no error handling in this library as a design choice. You will need to make sure that whatever you are passing is actually proper opus.

**Comment by stevenruidigao** [comment]
The main problem is that I think it should be proper opus (it's the stream coming from a VoiceReceiver). I have this issue when it listens to a browser based discord client but not the application based ones (the iOS and Windows apps are fine).

**Comment by OnkelTem** [comment]
It's still not clear.
In my case I pick a regular opus file and `opusnec` doesn't have any problems with it. But this library fails. So what do you mean "thin wrapper", around what?

**Comment by iCrawl** [comment]
Around libopus. https://opus-codec.org/

**Comment by BaybaraEvgeny** [comment]
@stevenruidigao  @iCrawl "I have this issue when it listens to a browser based discord client but not the application based ones (the iOS and Windows apps are fine). " Me too! Is it normal that a browser based discord client don't send proper opus? What should we do about it?

**Comment by JustroX** [comment]
I can also confirm that this happens when it listens to a browser based discord client.

**Comment by JMTK** [comment]
It also will sometimes fail mid-stream. I've had streams that were non-opus that threw this immediately, but I also had a stream that was opus and was mid-song when it threw the same error. I'm not sure if there's some sort of invalid packet within a stream that is "non-opus" that could also throw this

**Comment by Roguyt** [comment]
I can confirm that every time this issues occur it is linked to someone using the web client of Discord. Forcing them to use the desktop client seems to fix it permanently. On 26 Apr 2021 17:53, Jacob Morrison ***@***.***> wrote:
It also will sometimes fail mid-stream. I've had streams that were non-opus that threw this immediately, but I also had a stream that was opus and was mid-song when it threw the same error. I'm not sure if there's some sort of invalid packet within a stream that is "non-opus" that could also throw this

**Comment by LordFarquhar** [comment]
Hi there, from my experiences (literally solved this issue ten seconds ago) this occurs when a stream type that does not match the provided stream is given. 
For example, I was using ytdl-core and directly piping the stream to the discord.js dispatcher. When providing the option `{type: "opus"}` to the .play method, it would immediately crash the process and return a segmentation fault error (SIGSEGV). Removing the type and allowing discord to "guess" solved this issue for me.

Not sure if this is helpful but it at least seemed related. Hope this helped

**Comment by Am3nd** [comment]
Hi There, My issue turned out to be that I was setting an event listener twice. After fixing I have yet to see that error again.
