### ISSUE TITLE
what about the docs

### ISSUE THREAD

**Issue by davakh** [discordjs/opus#5]
Npm library `node-opus` is unmaintained and recommends to use this library instead. I know, it seems to you, maybe, unnecessary to add documentation for the library. But can you provide some readme and a few examples of usage? I think it can boost up the number of users for this library, cause now for me as a simple js-developer, not really obvious how to switch from `node-opus` to `@discordjs/opus` or even how to use this library. 

I would appreciate your help.

**Comment by iCrawl** [comment]
There is no functional difference between the 2.

```js
var opus = require('node-opus');

// Create the encoder.
// Specify 48kHz sampling rate and 10ms frame size.
// NOTE: The decoder must use the same values when decoding the packets.
var rate = 48000;
var encoder = new opus.OpusEncoder( rate );

// Encode and decode.
var frame_size = rate/100;
var encoded = encoder.encode( buffer, frame_size );
var decoded = encoder.decode( encoded, frame_size );

// or create streams
var channels = 2;
var opusEncodeStream = new opus.Encoder(rate, channels, frame_size);
var opusDecodeStream = new opus.Decoder(rate, channels, frame_size);
// see examples folder for a more complete example
```

in this example the only thing that does not work is the last 3 lines of code because the packages [ref-array](https://github.com/TooTallNate/ref-array), [ref-struct](https://github.com/TooTallNate/ref-struct) and [ogg-packet](https://github.com/TooTallNate/node-ogg-packet) are all broken on Node12+

**Comment by davakh** [comment]
It doesn't seem similar, cause when I'm trying to use it as I always use it with `node-opus`. Here's a node exception. Which is not really meaningful.
`Error: Could not create decoder. Check the decoder parameters`

And I use, as you said, just as `node-opus`:
```
const opus = require('@discordjs/opus');

const FRAME_SIZE = 5760;
const chunk = /* Buffer */
const sampleRate = 48000;

const opusEncoder = new opus.OpusEncoder(sampleRate);
const data = opusEncoder.decode(chunk, FRAME_SIZE); /* Here is an exception happens */
```

p.s.//
What do you mean about the last 3 lines, is it about arguments?

**Comment by iCrawl** [comment]
Can you try supplying a channels argument to the constructor?

`const opusEncoder = new opus.OpusEncoder(sampleRate, 2);`

**Comment by davakh** [comment]
Ye, it works with passing number of channels as the second argument. Thanks ❤️
