### ISSUE TITLE
Glibc version 2.28 missing

### ISSUE THREAD

**Issue by scorixear** [discordjs/opus#56]
I am using @discordjs/opus version 0.3.3 for playing youtube streams in my discord server.
I updated the opus library from 0.1.0 for 0.3.3 and node-pre-gyp cannot install the opus library now.

pastebin of npm: https://pastebin.com/gtdSvMpu
pastebin of console output: https://pastebin.com/72wvq02T

It seems like there is version 2.28 missing. Debian 10 uses the latest stable build of libc6 Version 2.28
as shown here. https://packages.debian.org/search?keywords=libc6

**Further details:**

- @discordjs/opus version: 0.3.3
- Node.js version: 13.3.0
- Operating system: Debian 10
- Priority this issue should have – please be realistic and elaborate if possible: My Project Priority - Highest, Your Priority - Middle

**Comment by iCrawl** [comment]
https://github.com/discordjs/opus/issues/43#issuecomment-716168497
