### ISSUE TITLE
Failing to install on Ubuntu 18.04 VPS

### ISSUE THREAD

**Issue by PhantomNimbi** [discordjs/opus#59]
**Please describe the problem you are having in as much detail as possible:**
Errors out on Ubuntu 18.04 VPS during install. It is one of the dependencies for Corion

**Include a reproducible code sample here, if possible:**

```js
npm i
```

and/or

```js
npm i @discordjs/opus
```

**Further details:**

- Error

```json
npm ERR! Linux 4.15.0-134-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "i" "@discordjs/opus"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE

npm ERR! @discordjs/opus@0.3.3 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @discordjs/opus@0.3.3 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the @discordjs/opus package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs @discordjs/opus
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls @discordjs/opus
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/mountaint-dev/Corion/npm-debug.log
```
- @discordjs/opus version: 0.3.3
- Node.js version:  8.10.0
- Operating system: Ubuntu 18.04
- Priority this issue should have – please be realistic and elaborate if possible:  Urgent. We need it to get our Music bot back up and running now that we got a new VPS.

**Comment by advaith1** [comment]
try updating Node? node 8 is very old and discord.js doesn't support it; looks like djs/opus doesn't have any documented version requirement but I'd recommend sticking with what djs supports (node 12+ for djs v12 and node 14+ for djs v13)

> npm ERR! Make sure you have the latest version of node.js and npm installed.

**Comment by PhantomNimbi** [comment]
yip, this fixed my issue. ty
