### ISSUE TITLE
npm module still on version 0.3.3

### ISSUE THREAD

**Issue by BR88C** [discordjs/opus#62]
I'm not entirely familiar with posting to npm, however it is still on version 0.3.3. Figured I'd open an issue in case this was overlooked.

**Comment by JediThePro** [comment]
Seems you don't kniw how to update.
Try this, to update npm:

`npm install -g npm`

**Comment by tipakA** [comment]
@JediThePro That... is completely not what they are talking about.
They are talking about the fact that this package had a 0.4.0 release that was not pushed to npm.

**Comment by AustinLeath** [comment]
They are probably still working on the release for npm

**Comment by iCrawl** [comment]
It is now.
