### ISSUE TITLE
RP4 Support?

### ISSUE THREAD

**Issue by Johannes7k75** [discordjs/opus#63]
**Is your feature request related to a problem? Please describe.**
Yes, the discord/opus cant be used on the RP4

**Describe the ideal solution**
A RP4 version from Discord/Opus

**Describe alternatives you've considered**
No, bc its the only way

**Comment by iCrawl** [comment]
I don't see why it wouldn't work.

Is the RP4 not running on ARMv64?

**Comment by Johannes7k75** [comment]
Thanks for the help i didn't read the README proberly. I had node.js on version 10. And i had think because there were not written in the README the support for RP4 , that it is not supported it work yet.

Another time thanks for the help.
