### ISSUE TITLE
404 Error when using "npm i @discordjs/opus@latest"

### ISSUE THREAD

**Issue by xSehrMotiviert** [discordjs/opus#67]
Hi, the url npm is using is not existing.

Please update it :)

// EDIT 1:
The URL npm is trying to use is: https://github.com/discordjs/opus/releases/download/v0.4.0/opus-v0.4.0-node-v83-napi-v3-linux-x64-glibc-2.28.tar.gz

// EDIT 2:
NodeJS Version: 14.15.5
NPM Version: 6.14.11

**Comment by xSehrMotiviert** [comment]
The URL npm is trying to use is: https://github.com/discordjs/opus/releases/download/v0.4.0/opus-v0.4.0-node-v83-napi-v3-linux-x64-glibc-2.28.tar.gz

**Comment by xSehrMotiviert** [comment]
NodeJS Version: 14.15.5
NPM Version: 6.14.11

**Comment by iCrawl** [comment]
There is nothing to be done here.

We don't prebuild every single version known to humanity, if a certain build cannot be found it will attempt to build it on the system you try to install it.
