### ISSUE TITLE
Getting gyp errors when running npm install

### ISSUE THREAD

**Issue by Cowation** [discordjs/opus#71]
**Please describe the problem you are having in as much detail as possible:**

Recently I cloned the source for one of my Discord bots onto my laptop and downloaded Python along with the Visual Studio C++ build tools. After running `npm install` to install the needed dependencies, I was greeted with a long string of errors in my console.

**Include a reproducible code sample here, if possible:**

Run `npm install @discordjs/opus` on a Windows 10 64-bit machine with the Microsoft Store Python 3.9 package and the Visual Studio 2019 C++ Build Tools.

**Further details:**

Console output:
```console
$ npm install
npm WARN deprecated node-pre-gyp@0.15.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future
npm ERR! code 1
npm ERR! path C:\Users\knoddy\Desktop\ogs-bot\node_modules\@discordjs\opus
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node-gyp rebuild
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@14.15.5 | win32 | x64
npm ERR! gyp info find Python using Python version 3.9.2 found at "C:\Users\knoddy\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\python.exe"
npm ERR! gyp info find VS using VS2019 (16.9.31025.194) found at:
npm ERR! gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools"
npm ERR! gyp info find VS run with --verbose for detailed information
npm ERR! gyp info spawn C:\Users\knoddy\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\python.exe
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   'C:\\Users\\knoddy\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'msvs',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Users\\knoddy\\Desktop\\ogs-bot\\node_modules\\@discordjs\\opus\\build\\config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Users\\knoddy\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Users\\knoddy\\AppData\\Local\\node-gyp\\Cache\\14.15.5\\include\\node\\common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=C:\\Users\\knoddy\\AppData\\Local\\node-gyp\\Cache\\14.15.5',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\knoddy\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\knoddy\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\14.15.5\\\\<(target_arch)\\\\node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\knoddy\\Desktop\\ogs-bot\\node_modules\\@discordjs\\opus',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'C:\\Users\\knoddy\\Desktop\\ogs-bot\\node_modules\\@discordjs\\opus\\build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp: Undefined variable module_name in binding.gyp while trying to load binding.gyp
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\knoddy\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:351:16)
npm ERR! gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
npm ERR! gyp ERR! System Windows_NT 10.0.18363
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\knoddy\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd C:\Users\knoddy\Desktop\ogs-bot\node_modules\@discordjs\opus
npm ERR! gyp ERR! node -v v14.15.5
npm ERR! gyp ERR! node-gyp -v v7.1.2
npm ERR! gyp ERR! not ok
```

- @discordjs/opus version: 0.4.0 (attempting to install)
- Node.js version: v14.15.5
- Operating system: Windows 10 64-bit
- Priority this issue should have – please be realistic and elaborate if possible: Medium

**Comment by xAtsuUC** [comment]
Please try with [this](https://github.com/nodejs/node-gyp/issues/508)

**Comment by Cowation** [comment]
Thanks for the quick reply. However, I'm not sure how I would go about fixing the issue. Do I need to edit other files before running the installation command?

**Comment by xAtsuUC** [comment]
![image](https://user-images.githubusercontent.com/67171928/110167051-f3fdcc80-7dd3-11eb-805d-7904c50a9d9b.png)

**Comment by Cowation** [comment]
Thank you very much, this solved my problem.

**Comment by xAtsuUC** [comment]
No problem!

**Comment by Cowation** [comment]
Yikes, when I ran `node index.js` to start the bot, I got yet another error. Here's the output:

```console
$ node .
C:\Users\knoddy\Desktop\ogs-bot\node_modules\bindings\bindings.js:135
  throw err;
  ^

Error: Could not locate the bindings file. Tried:
 → C:\Users\knoddy\Desktop\ogs-bot\node_modules\node-expat\build\node_expat.node
 → C:\Users\knoddy\Desktop\ogs-bot\node_modules\node-expat\build\Debug\node_expat.node
 → C:\Users\knoddy\Desktop\ogs-bot\node_modules\node-expat\build\Release\node_expat.node
 → C:\Users\knoddy\Desktop\ogs-bot\node_modules\node-expat\out\Debug\node_expat.node
 → C:\Users\knoddy\Desktop\ogs-bot\node_modules\node-expat\Debug\node_expat.node
 → C:\Users\knoddy\Desktop\ogs-bot\node_modules\node-expat\out\Release\node_expat.node
 → C:\Users\knoddy\Desktop\ogs-bot\node_modules\node-expat\Release\node_expat.node
 → C:\Users\knoddy\Desktop\ogs-bot\node_modules\node-expat\build\default\node_expat.node
 → C:\Users\knoddy\Desktop\ogs-bot\node_modules\node-expat\compiled\14.15.5\win32\x64\node_expat.node
 → C:\Users\knoddy\Desktop\ogs-bot\node_modules\node-expat\addon-build\release\install-root\node_expat.node
 → C:\Users\knoddy\Desktop\ogs-bot\node_modules\node-expat\addon-build\debug\install-root\node_expat.node
 → C:\Users\knoddy\Desktop\ogs-bot\node_modules\node-expat\addon-build\default\install-root\node_expat.node
 → C:\Users\knoddy\Desktop\ogs-bot\node_modules\node-expat\lib\binding\node-v83-win32-x64\node_expat.node
    at bindings (C:\Users\knoddy\Desktop\ogs-bot\node_modules\bindings\bindings.js:126:9)
    at Object.<anonymous> (C:\Users\knoddy\Desktop\ogs-bot\node_modules\node-expat\lib\node-expat.js:4:32)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\Users\knoddy\Desktop\ogs-bot\node_modules\xml2json\lib\xml2json.js:1:13)
    at Module._compile (internal/modules/cjs/loader.js:1063:30) {
  tries: [
    'C:\\Users\\knoddy\\Desktop\\ogs-bot\\node_modules\\node-expat\\build\\node_expat.node',
    'C:\\Users\\knoddy\\Desktop\\ogs-bot\\node_modules\\node-expat\\build\\Debug\\node_expat.node',
    'C:\\Users\\knoddy\\Desktop\\ogs-bot\\node_modules\\node-expat\\build\\Release\\node_expat.node',
    'C:\\Users\\knoddy\\Desktop\\ogs-bot\\node_modules\\node-expat\\out\\Debug\\node_expat.node',
    'C:\\Users\\knoddy\\Desktop\\ogs-bot\\node_modules\\node-expat\\Debug\\node_expat.node',
    'C:\\Users\\knoddy\\Desktop\\ogs-bot\\node_modules\\node-expat\\out\\Release\\node_expat.node',
    'C:\\Users\\knoddy\\Desktop\\ogs-bot\\node_modules\\node-expat\\Release\\node_expat.node',
    'C:\\Users\\knoddy\\Desktop\\ogs-bot\\node_modules\\node-expat\\build\\default\\node_expat.node',
    'C:\\Users\\knoddy\\Desktop\\ogs-bot\\node_modules\\node-expat\\compiled\\14.15.5\\win32\\x64\\node_expat.node',
    'C:\\Users\\knoddy\\Desktop\\ogs-bot\\node_modules\\node-expat\\addon-build\\release\\install-root\\node_expat.node',
    'C:\\Users\\knoddy\\Desktop\\ogs-bot\\node_modules\\node-expat\\addon-build\\debug\\install-root\\node_expat.node',
    'C:\\Users\\knoddy\\Desktop\\ogs-bot\\node_modules\\node-expat\\addon-build\\default\\install-root\\node_expat.node',
    'C:\\Users\\knoddy\\Desktop\\ogs-bot\\node_modules\\node-expat\\lib\\binding\\node-v83-win32-x64\\node_expat.node'
  ]
}
```

**Comment by xAtsuUC** [comment]
I found [this](https://stackoverflow.com/questions/39002144/error-could-not-locate-the-bindings-file-tried) solution in StackOverflow, try it and tell me if there's any new error or something.

**Comment by Cowation** [comment]
Thanks for the link. Do you happen to know what parameters I should be using when running node-gyp? I think the thread is talking about some other module.

**Comment by xAtsuUC** [comment]
I don't exactly know, you should go get some info about the modules that you are using, both of that responses were found by me in (Bing)[https://bing.com] and (StackOverflow)[https://stackoverflow.com/]

**Comment by Cowation** [comment]
Oh, I just re-ran the commands that you sent before and all of a sudden it worked! I just had to delete my node_modules folder and install the dependencies again. Thanks for the help!

**Comment by xAtsuUC** [comment]
Again, no problem, have a nice day!

**Comment by kalmi7223** [comment]
i also need help with it i ran pnpm install but i have a problem in discord opus and voice , i get error code 7 and 1 , ihave node js version 23 
heres the output
`pnpm install
 WARN  19 deprecated subdependencies found: @cliqz/adblocker-content@1.34.0, @cliqz/adblocker-extended-selectors@1.34.0, @cliqz/adblocker-playwright@1.34.0, @cliqz/adblocker@1.34.0, @discordjs/voice@0.17.0, are-we-there-yet@2.0.0, are-we-there-yet@3.0.1, bin-version-check@6.0.0, gauge@3.0.2, gauge@4.0.4, glob@7.2.3, har-validator@5.1.5, inflight@1.0.6, npmlog@5.0.1, npmlog@6.0.2, puppeteer@19.11.1, request@2.88.2, rimraf@3.0.2, uuid@3.4.0
Packages: +1331
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Progress: resolved 1433, reused 1332, downloaded 0, added 0, done
node_modules/.pnpm/canvas@2.11.2/node_modules/canvas: Running install script...
node_modules/.pnpm/canvas@2.11.2/node_modules/canvas: Running install script, failed in 5.5s (skipped as optional).
node_modules/.pnpm/node-llama-cpp@3.1.1_typescript@5.6.3/node_modules/node-llama-cpp: Running postinstall script, done inode_modules/.pnpm/@discordjs+opus@https+++codeload.github.com+discordjs+opus+tar.gz+31da49d8d2cc6c5a2ab1bfd332033ff7d5f9fb02/node_modules/@discordjs/opus: Running install script, failed in 5.8s
.../node_modules/@discordjs/opus install$ node-pre-gyp install --fallback-to-build
│ node-pre-gyp info it worked if it ends with ok
│ node-pre-gyp info using node-pre-gyp@0.4.5
│ node-pre-gyp info using node@23.4.0 | win32 | x64
│ (node:8860) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative in…
│ (Use `node --trace-deprecation ...` to show where the warning was created)
│ node-pre-gyp info check checked for "C:\Users\dawgs\Eliza\eliza-starter\node_modules\.pnpm\@discordjs+opus@https+++…
│ node-pre-gyp http GET https://github.com/discordjs/opus/releases/download/v0.9.0/opus-v0.9.0-node-v131-napi-v3-win3…
│ node-pre-gyp ERR! install response status 404 Not Found on https://github.com/discordjs/opus/releases/download/v0.9…
│ node-pre-gyp WARN Pre-built binaries not installable for @discordjs/opus@0.9.0 and node@23.4.0 (node-v131 ABI, unkn…
│ node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/discordjs/opus/releases/download/v0…
│ gyp info it worked if it ends with ok
│ gyp info using node-gyp@10.2.0
│ gyp info using node@23.4.0 | win32 | x64
│ gyp info ok
│ gyp info it worked if it ends with ok
│ gyp info using node-gyp@10.2.0
│ gyp info using node@23.4.0 | win32 | x64
│ gyp info find Python using Python version 3.13.1 found at "C:\Users\dawgs\AppData\Local\Programs\Python\Python313\p…
│ gyp info find VS using VS2022 (17.12.35527.113) found at:
│ gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools"
│ gyp info find VS run with --verbose for detailed information
│ gyp info spawn C:\Users\dawgs\AppData\Local\Programs\Python\Python313\python.exe
│ gyp info spawn args [
│ gyp info spawn args 'C:\\Users\\dawgs\\AppData\\Roaming\\npm\\node_modules\\pnpm\\dist\\node_modules\\node-gyp\\gyp…
│ gyp info spawn args 'binding.gyp',
│ gyp info spawn args '-f',
│ gyp info spawn args 'msvs',
│ gyp info spawn args '-I',
│ gyp info spawn args 'C:\\Users\\dawgs\\Eliza\\eliza-starter\\node_modules\\.pnpm\\@discordjs+opus@https+++codeload.…
│ gyp info spawn args '-I',
│ gyp info spawn args 'C:\\Users\\dawgs\\AppData\\Roaming\\npm\\node_modules\\pnpm\\dist\\node_modules\\node-gyp\\add…
│ gyp info spawn args '-I',
│ gyp info spawn args 'C:\\Users\\dawgs\\AppData\\Local\\node-gyp\\Cache\\23.4.0\\include\\node\\common.gypi',
│ gyp info spawn args '-Dlibrary=shared_library',
│ gyp info spawn args '-Dvisibility=default',
│ gyp info spawn args '-Dnode_root_dir=C:\\Users\\dawgs\\AppData\\Local\\node-gyp\\Cache\\23.4.0',
│ gyp info spawn args '-Dnode_gyp_dir=C:\\Users\\dawgs\\AppData\\Roaming\\npm\\node_modules\\pnpm\\dist\\node_modules…
│ gyp info spawn args '-Dnode_lib_file=C:\\\\Users\\\\dawgs\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\23.4.0\\\\<(t…
│ gyp info spawn args '-Dmodule_root_dir=C:\\Users\\dawgs\\Eliza\\eliza-starter\\node_modules\\.pnpm\\@discordjs+opus…
│ gyp info spawn args '-Dnode_engine=v8',
│ gyp info spawn args '--depth=.',
│ gyp info spawn args '--no-parallel',
│ gyp info spawn args '--generator-output',
│ gyp info spawn args 'C:\\Users\\dawgs\\Eliza\\eliza-starter\\node_modules\\.pnpm\\@discordjs+opus@https+++codeload.…
│ gyp info spawn args '-Goutput_dir=.'
│ gyp info spawn args ]
│ <string>:43: SyntaxWarning: invalid escape sequence '\$'
│ gyp info ok
│ gyp info it worked if it ends with ok
│ gyp info using node-gyp@10.2.0
│ gyp info using node@23.4.0 | win32 | x64
│ gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\MSBuild.exe
│ gyp info spawn args [
│ gyp info spawn args 'build\\binding.sln',
│ gyp info spawn args '/clp:Verbosity=minimal',
│ gyp info spawn args '/nologo',
│ gyp info spawn args '/p:Configuration=Release;Platform=x64'
│ gyp info spawn args ]
│   opus_multistream.c
│   opus_projection_encoder.c
│ C:\Users\dawgs\Eliza\eliza-starter\node_modules\.pnpm\@discordjs+opus@https+++codeload.github.com+discordjs+opus+ta…
│ gyp ERR! build error
│ gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\MSBuild.e…
│ gyp ERR! stack at ChildProcess.<anonymous> (C:\Users\dawgs\AppData\Roaming\npm\node_modules\pnpm\dist\node_modules\…
│ gyp ERR! stack at ChildProcess.emit (node:events:513:28)
│ gyp ERR! stack at ChildProcess._handle.onexit (node:internal/child_process:294:12)
│ gyp ERR! System Windows_NT 10.0.26100
│ gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\dawgs\\AppData\\Roaming\\npm\\node_modules\\pnpm…
│ gyp ERR! cwd C:\Users\dawgs\Eliza\eliza-starter\node_modules\.pnpm\@discordjs+opus@https+++codeload.github.com+disc…
│ gyp ERR! node -v v23.4.0
│ gyp ERR! node-gyp -v v10.2.0
│ gyp ERR! not ok
│ node-pre-gyp ERR! build error
│ node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\dawgs\AppData\Roaming\n…
│ node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\dawgs\Eliza\eliza-starter\node_modules\.pnpm\@dis…
│ node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
│ node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1101:16)
│ node-pre-gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:305:5)
│ node-pre-gyp ERR! System Windows_NT 10.0.26100
│ node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\dawgs\\Eliza\\eliza-starter\\node_modul…
│ Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\dawgs\AppData\Roaming\npm\node_modules\pnpm\dist\node_…
│ node-pre-gyp ERR! cwd C:\Users\dawgs\Eliza\eliza-starter\node_modules\.pnpm\@discordjs+opus@https+++codeload.github…
│ node-pre-gyp ERR! node -v v23.4.0
│ node-pre-gyp ERR! node-pre-gyp -v v0.4.5
│ node-pre-gyp ERR! not ok
└─ Failed in 5.8s at C:\Users\dawgs\Eliza\eliza-starter\node_modules\.pnpm\@discordjs+opus@https+++codeload.github.com+discordjs+opus+tar.gz+31da49d8d2cc6c5a2ab1bfd332033ff7d5f9fb02\node_modules\@discordjs\opus
 ELIFECYCLE  Command failed with exit code 1.`

**Comment by ameeetgaikwad** [comment]
> i also need help with it i ran pnpm install but i have a problem in discord opus and voice , i get error code 7 and 1 , ihave node js version 23 heres the output `pnpm install  WARN  19 deprecated subdependencies found: @cliqz/adblocker-content@1.34.0, @cliqz/adblocker-extended-selectors@1.34.0, @cliqz/adblocker-playwright@1.34.0, @cliqz/adblocker@1.34.0, @discordjs/voice@0.17.0, are-we-there-yet@2.0.0, are-we-there-yet@3.0.1, bin-version-check@6.0.0, gauge@3.0.2, gauge@4.0.4, glob@7.2.3, har-validator@5.1.5, inflight@1.0.6, npmlog@5.0.1, npmlog@6.0.2, puppeteer@19.11.1, request@2.88.2, rimraf@3.0.2, uuid@3.4.0 Packages: +1331 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ Progress: resolved 1433, reused 1332, downloaded 0, added 0, done node_modules/.pnpm/canvas@2.11.2/node_modules/canvas: Running install script... node_modules/.pnpm/canvas@2.11.2/node_modules/canvas: Running install script, failed in 5.5s (skipped as optional). node_modules/.pnpm/node-llama-cpp@3.1.1_typescript@5.6.3/node_modules/node-llama-cpp: Running postinstall script, done inode_modules/.pnpm/@discordjs+opus@https+++codeload.github.com+discordjs+opus+tar.gz+31da49d8d2cc6c5a2ab1bfd332033ff7d5f9fb02/node_modules/@discordjs/opus: Running install script, failed in 5.8s .../node_modules/@discordjs/opus install$ node-pre-gyp install --fallback-to-build │ node-pre-gyp info it worked if it ends with ok │ node-pre-gyp info using node-pre-gyp@0.4.5 │ node-pre-gyp info using node@23.4.0 | win32 | x64 │ (node:8860) [DEP0040] DeprecationWarning: The `punycode`module is deprecated. Please use a userland alternative in… │ (Use`node --trace-deprecation ...`to show where the warning was created) │ node-pre-gyp info check checked for "C:\Users\dawgs\Eliza\eliza-starter\node_modules\.pnpm\@discordjs+opus@https+++… │ node-pre-gyp http GET https://github.com/discordjs/opus/releases/download/v0.9.0/opus-v0.9.0-node-v131-napi-v3-win3… │ node-pre-gyp ERR! install response status 404 Not Found on https://github.com/discordjs/opus/releases/download/v0.9… │ node-pre-gyp WARN Pre-built binaries not installable for @discordjs/opus@0.9.0 and node@23.4.0 (node-v131 ABI, unkn… │ node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/discordjs/opus/releases/download/v0… │ gyp info it worked if it ends with ok │ gyp info using node-gyp@10.2.0 │ gyp info using node@23.4.0 | win32 | x64 │ gyp info ok │ gyp info it worked if it ends with ok │ gyp info using node-gyp@10.2.0 │ gyp info using node@23.4.0 | win32 | x64 │ gyp info find Python using Python version 3.13.1 found at "C:\Users\dawgs\AppData\Local\Programs\Python\Python313\p… │ gyp info find VS using VS2022 (17.12.35527.113) found at: │ gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools" │ gyp info find VS run with --verbose for detailed information │ gyp info spawn C:\Users\dawgs\AppData\Local\Programs\Python\Python313\python.exe │ gyp info spawn args [ │ gyp info spawn args 'C:\\Users\\dawgs\\AppData\\Roaming\\npm\\node_modules\\pnpm\\dist\\node_modules\\node-gyp\\gyp… │ gyp info spawn args 'binding.gyp', │ gyp info spawn args '-f', │ gyp info spawn args 'msvs', │ gyp info spawn args '-I', │ gyp info spawn args 'C:\\Users\\dawgs\\Eliza\\eliza-starter\\node_modules\\.pnpm\\@discordjs+opus@https+++codeload.… │ gyp info spawn args '-I', │ gyp info spawn args 'C:\\Users\\dawgs\\AppData\\Roaming\\npm\\node_modules\\pnpm\\dist\\node_modules\\node-gyp\\add… │ gyp info spawn args '-I', │ gyp info spawn args 'C:\\Users\\dawgs\\AppData\\Local\\node-gyp\\Cache\\23.4.0\\include\\node\\common.gypi', │ gyp info spawn args '-Dlibrary=shared_library', │ gyp info spawn args '-Dvisibility=default', │ gyp info spawn args '-Dnode_root_dir=C:\\Users\\dawgs\\AppData\\Local\\node-gyp\\Cache\\23.4.0', │ gyp info spawn args '-Dnode_gyp_dir=C:\\Users\\dawgs\\AppData\\Roaming\\npm\\node_modules\\pnpm\\dist\\node_modules… │ gyp info spawn args '-Dnode_lib_file=C:\\\\Users\\\\dawgs\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\23.4.0\\\\<(t… │ gyp info spawn args '-Dmodule_root_dir=C:\\Users\\dawgs\\Eliza\\eliza-starter\\node_modules\\.pnpm\\@discordjs+opus… │ gyp info spawn args '-Dnode_engine=v8', │ gyp info spawn args '--depth=.', │ gyp info spawn args '--no-parallel', │ gyp info spawn args '--generator-output', │ gyp info spawn args 'C:\\Users\\dawgs\\Eliza\\eliza-starter\\node_modules\\.pnpm\\@discordjs+opus@https+++codeload.… │ gyp info spawn args '-Goutput_dir=.' │ gyp info spawn args ] │ <string>:43: SyntaxWarning: invalid escape sequence '\$' │ gyp info ok │ gyp info it worked if it ends with ok │ gyp info using node-gyp@10.2.0 │ gyp info using node@23.4.0 | win32 | x64 │ gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\MSBuild.exe │ gyp info spawn args [ │ gyp info spawn args 'build\\binding.sln', │ gyp info spawn args '/clp:Verbosity=minimal', │ gyp info spawn args '/nologo', │ gyp info spawn args '/p:Configuration=Release;Platform=x64' │ gyp info spawn args ] │ opus_multistream.c │ opus_projection_encoder.c │ C:\Users\dawgs\Eliza\eliza-starter\node_modules\.pnpm\@discordjs+opus@https+++codeload.github.com+discordjs+opus+ta… │ gyp ERR! build error │ gyp ERR! stack Error:`C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\MSBuild.e… │ gyp ERR! stack at ChildProcess. (C:\Users\dawgs\AppData\Roaming\npm\node_modules\pnpm\dist\node_modules\… │ gyp ERR! stack at ChildProcess.emit (node:events:513:28) │ gyp ERR! stack at ChildProcess._handle.onexit (node:internal/child_process:294:12) │ gyp ERR! System Windows_NT 10.0.26100 │ gyp ERR! command "C:\Program Files\nodejs\node.exe" "C:\Users\dawgs\AppData\Roaming\npm\node_modules\pnpm… │ gyp ERR! cwd C:\Users\dawgs\Eliza\eliza-starter\node_modules.pnpm@discordjs+opus@https+++codeload.github.com+disc… │ gyp ERR! node -v v23.4.0 │ gyp ERR! node-gyp -v v10.2.0 │ gyp ERR! not ok │ node-pre-gyp ERR! build error │ node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\dawgs\AppData\Roaming\n… │ node-pre-gyp ERR! stack at ChildProcess. (C:\Users\dawgs\Eliza\eliza-starter\node_modules.pnpm@dis… │ node-pre-gyp ERR! stack at ChildProcess.emit (node:events:513:28) │ node-pre-gyp ERR! stack at maybeClose (node:internal/child_process:1101:16) │ node-pre-gyp ERR! stack at ChildProcess._handle.onexit (node:internal/child_process:305:5) │ node-pre-gyp ERR! System Windows_NT 10.0.26100 │ node-pre-gyp ERR! command "C:\Program Files\nodejs\node.exe" "C:\Users\dawgs\Eliza\eliza-starter\node_modul… │ Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\dawgs\AppData\Roaming\npm\node_modules\pnpm\dist\node_… │ node-pre-gyp ERR! cwd C:\Users\dawgs\Eliza\eliza-starter\node_modules.pnpm@discordjs+opus@https+++codeload.github… │ node-pre-gyp ERR! node -v v23.4.0 │ node-pre-gyp ERR! node-pre-gyp -v v0.4.5 │ node-pre-gyp ERR! not ok └─ Failed in 5.8s at C:\Users\dawgs\Eliza\eliza-starter\node_modules.pnpm@discordjs+opus@https+++codeload.github.com+discordjs+opus+tar.gz+31da49d8d2cc6c5a2ab1bfd332033ff7d5f9fb02\node_modules@discordjs\opus  ELIFECYCLE  Command failed with exit code 1.`

hey @kalmi7223 facing same issue, did you find any solution?

**Comment by ErrorRExorY** [comment]
If anyone has the same Problem and came across this, here is the command that will install all necessary packages via apt on ubuntu to fix this. I don't know if you really need all packages in the command, but this has fixed it for me:

`apt update && apt install -y build-essential python3 make g++`
My first guess is, that you probably only need the build-essentials and g++ for it to work, since you need to compile opus voice in order to install it. Works on dedicated and vserver. TESTED
