### ISSUE TITLE
Can't download using the npm install command

### ISSUE THREAD

**Issue by labrosggv** [discordjs/opus#73]
I am trying to download it using npm install @discordjs/opus but it doesn't work

**Comment by advaith1** [comment]
it's `install` not `imstall`

if you did type `install` then what is the error? and did you look at the issue templates? https://github.com/discordjs/opus/issues/new/choose

**Comment by labrosggv** [comment]
> it's `install` not `imstall`
> 
> if you did type `install` then what is the error? and did you look at the issue templates? https://github.com/discordjs/opus/issues/new/choose

I typed install
