### ISSUE TITLE
npm rebuild producing weird filenames

### ISSUE THREAD

**Issue by portasynthinca3** [discordjs/opus#77]
I'm not sure if this is an issue with the module itself, `node-gyp` or even `npm`, but I'll post it here. Please redirect me if this is not the place to ask.

The first directory in the screenshot below was produced by `electron-rebuild`, the second one was produced by `npm rebuild`. Of course, the module fails to load because it looks like `napi_build_version` and `libc_version` have not been substituted somehow.
![image](https://user-images.githubusercontent.com/14039901/112285852-cc47a900-8c9b-11eb-8e59-3521a42a2539.png)

If I were to manually rename these directories like so:
![image](https://user-images.githubusercontent.com/14039901/112286453-63acfc00-8c9c-11eb-90b9-018ba7750504.png)
It works just fine

**Comment by iCrawl** [comment]
You'll have to use `@discordjs/node-pre-gyp` to rebuild in this case.

`napi_build_version` and `libc_version` are custom to the module.

**Comment by portasynthinca3** [comment]
Great! It works, thank you :+1:
