### ISSUE TITLE
I can't install @discordjs/opus by npm

### ISSUE THREAD

**Issue by Bount23** [discordjs/opus#78]
Hello, 
I apologize, it's not really a mistake, but I can't install @discordjs/opus and I don't know where to put this kind of problem. I encounter this error:

root@XXXXXXXX: #npm install @discordjs/opus
npm ERR! code 127
npm ERR! path /root/.nvm/versions/node/v14.16.0/lib/node_modules/@discordjs/opus
npm ERR! command failed
npm ERR! command sh -c node-pre-gyp install --fallback-to-build
npm ERR! sh: 1: node-pre-gyp: Permission denied

npm ERR! A complete log of this run can be found in:
npm ERR!    /root/.npm/_logs/2021-03-25T21_15_40_306Z-debug.log

**Comment by iCrawl** [comment]
Permission issues have nothing to do with this library.
