### ISSUE TITLE
the bot I am hosting over AWS doesn't seem to find the modules

### ISSUE THREAD

**Issue by dertypjustin** [discordjs/opus#80]
the bot I am hosting over AWS doesn't seem to find the modules even though i tried installing everything that is necessary multiple times already. I even downloaded the files straight from GitHub and placed them inside of the right folders. But it still gives me the same errors everytime i try to play a song. I even stopped the server and hosted it locally with the same modules and everything and then it worked fine.

0|main  | Error: Error: Cannot find module '@discordjs/opus'
0|main  | Require stack:
0|main  | - /home/ec2-user/Bot/node_modules/prism-media/src/util/loader.js
0|main  | - /home/ec2-user/Bot/node_modules/prism-media/src/opus/Opus.js
0|main  | - /home/ec2-user/Bot/node_modules/prism-media/src/opus/index.js
0|main  | - /home/ec2-user/Bot/node_modules/prism-media/src/index.js
0|main  | - /home/ec2-user/Bot/node_modules/discord.js/src/client/voice/player/BasePlayer.js
0|main  | - /home/ec2-user/Bot/node_modules/discord.js/src/client/voice/player/BroadcastAudioPlayer.js
0|main  | - /home/ec2-user/Bot/node_modules/discord.js/src/client/voice/VoiceBroadcast.js
0|main  | - /home/ec2-user/Bot/node_modules/discord.js/src/client/voice/ClientVoiceManager.js
0|main  | - /home/ec2-user/Bot/node_modules/discord.js/src/client/Client.js
0|main  | - /home/ec2-user/Bot/node_modules/discord.js/src/index.js
0|main  | - /home/ec2-user/Bot/main.js
0|main  | Error: Cannot find module 'node-opus'
0|main  | Require stack:
0|main  | - /home/ec2-user/Bot/node_modules/prism-media/src/util/loader.js
0|main  | - /home/ec2-user/Bot/node_modules/prism-media/src/opus/Opus.js
0|main  | - /home/ec2-user/Bot/node_modules/prism-media/src/opus/index.js
0|main  | - /home/ec2-user/Bot/node_modules/prism-media/src/index.js
0|main  | - /home/ec2-user/Bot/node_modules/discord.js/src/client/voice/player/BasePlayer.js
0|main  | - /home/ec2-user/Bot/node_modules/discord.js/src/client/voice/player/BroadcastAudioPlayer.js
0|main  | - /home/ec2-user/Bot/node_modules/discord.js/src/client/voice/VoiceBroadcast.js
0|main  | - /home/ec2-user/Bot/node_modules/discord.js/src/client/voice/ClientVoiceManager.js
0|main  | - /home/ec2-user/Bot/node_modules/discord.js/src/client/Client.js
0|main  | - /home/ec2-user/Bot/node_modules/discord.js/src/index.js
0|main  | - /home/ec2-user/Bot/main.js
0|main  | Error: Cannot find module 'opusscript'
0|main  | Require stack:
0|main  | - /home/ec2-user/Bot/node_modules/prism-media/src/util/loader.js
0|main  | - /home/ec2-user/Bot/node_modules/prism-media/src/opus/Opus.js
0|main  | - /home/ec2-user/Bot/node_modules/prism-media/src/opus/index.js
0|main  | - /home/ec2-user/Bot/node_modules/prism-media/src/index.js
0|main  | - /home/ec2-user/Bot/node_modules/discord.js/src/client/voice/player/BasePlayer.js
0|main  | - /home/ec2-user/Bot/node_modules/discord.js/src/client/voice/player/BroadcastAudioPlayer.js
0|main  | - /home/ec2-user/Bot/node_modules/discord.js/src/client/voice/VoiceBroadcast.js
0|main  | - /home/ec2-user/Bot/node_modules/discord.js/src/client/voice/ClientVoiceManager.js
0|main  | - /home/ec2-user/Bot/node_modules/discord.js/src/client/Client.js
0|main  | - /home/ec2-user/Bot/node_modules/discord.js/src/index.js
0|main  | - /home/ec2-user/Bot/main.js
0|main  |     at Object.loader [as require] (/home/ec2-user/Bot/node_modules/prism-media/src/util/loader.js:12:9)
0|main  |     at loadOpus (/home/ec2-user/Bot/node_modules/prism-media/src/opus/Opus.js:17:17)
0|main  |     at new OpusStream (/home/ec2-user/Bot/node_modules/prism-media/src/opus/Opus.js:46:10)
0|main  |     at new Encoder (/home/ec2-user/Bot/node_modules/prism-media/src/opus/Opus.js:149:5)
0|main  |     at AudioPlayer.playPCMStream (/home/ec2-user/Bot/node_modules/discord.js/src/client/voice/player/BasePlayer.js:58:34)
0|main  |     at AudioPlayer.playUnknown (/home/ec2-user/Bot/node_modules/discord.js/src/client/voice/player/BasePlayer.js:53:17)
0|main  |     at VoiceConnection.play (/home/ec2-user/Bot/node_modules/discord.js/src/client/voice/util/PlayInterface.js:71:28)
0|main  |     at video_player (/home/ec2-user/Bot/commands/play.js:95:27)
0|main  |     at Object.execute (/home/ec2-user/Bot/commands/play.js:67:21)
0|main  |     at processTicksAndRejections (internal/process/task_queues.js:93:5)

- @discordjs/opus version: 0.5.0
- Node.js version: 14.16.0
- Operating system: Red Hat Enterprise Linux
- Priority this issue should have – please be realistic and elaborate if possible:
somewhat high i guess

**Comment by iCrawl** [comment]
You use `npm` to install those modules. Those errors are not helpful and not fault of this library.
