### ISSUE TITLE
npm install @discordjs/opus installation error Win10

### ISSUE THREAD

**Issue by Denoxph** [discordjs/opus#81]
Can't install @discordjs/opus with npm

Comand: npm install @discordjs/opus

PS C:\Scripte&Programme\Discord Bots\Test> npm install @discordjs/opus                                  

> @discordjs/opus@0.5.0 install C:\Scripte&Programme\Discord Bots\Test\node_modules\@discordjs\opus
> node-pre-gyp install --fallback-to-build

Das System kann den angegebenen Pfad nicht finden.
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'C:\@discordjs\node-pre-gyp\bin\node-pre-gyp'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)        
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
npm WARN discordbot@1.0.0 No description      
npm WARN discordbot@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @discordjs/opus@0.5.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @discordjs/opus@0.5.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.     

npm ERR! A complete log of this run can be found in:

**Further details:**

- @discordjs/opus version:
- Node.js version: v14.16.1
- Operating system: Windows 10
- Priority this issue should have – please be realistic and elaborate if possible:

**Comment by Denoxph** [comment]
@discordjs/opus version: 0.5.0

**Comment by iCrawl** [comment]
`Error: Cannot find module 'C:@discordjs\node-pre-gyp\bin\node-pre-gyp'`

That doesn't look right, but also not really something I can reproduce.

**Comment by phamleduy04** [comment]
@Denoxph  Did you try to open powershell as admin and run `npm i -g windows-build-tools` ?

**Comment by Denoxph** [comment]
yes i did but i got the same result

**Comment by Denoxph** [comment]
![image](https://user-images.githubusercontent.com/53001882/117314043-b3c7d280-ae86-11eb-9712-05379dce8d91.png)

I just tried again with the command but its stuck and won't continue.

**Comment by Denoxph** [comment]
I think i fpund the Problem.
When i start npm install he searches for @discordjs in the directory c:/@discordjs. But my discordjs folder is in another folder:
"C:\Scripte&Programme\Discord Bots\Discord-Bot\node_modules\@discordjs"

![image](https://user-images.githubusercontent.com/53001882/117315034-9ba48300-ae87-11eb-9872-b2f3f74aa611.png)

can i somehow tell him to use my real @discordjs directory?

**Comment by kr3mil** [comment]
I had this exact issue, didn't work on my pc but when i tried on my laptop it seemed to work fine. I got this working on my pc by fully uninstalling node and npm, then installing the same version i had on my laptop (node v15.4.0)

**Comment by iCrawl** [comment]
Yeah this isn't really something I have control over, or can change on a library level.
