### ISSUE TITLE
I can't install @ discordjs / opus

### ISSUE THREAD

**Issue by stepkrep** [discordjs/opus#83]
I ran the npm i @ discordjs / opus command and it gives me this error. 

npm log file:
https://paste.ofcode.org/UUTKfkyx3P9Jc4y27e9GUs

Console:
https://paste.ofcode.org/32cupXZzesDFUqApjgHMkBg

I can't find the problem ... Please help me

Windows 10 19042.928
node@15.14.0
Python 3.9.4

**Comment by iCrawl** [comment]
Can you also attach the error you get in your console? The npm log file is not very helpful here.

**Comment by stepkrep** [comment]
https://paste.ofcode.org/32cupXZzesDFUqApjgHMkBg

**Comment by stepkrep** [comment]
> Can you also attach the error you get in your console? The npm log file is not very helpful here.

https://paste.ofcode.org/32cupXZzesDFUqApjgHMkBg

**Comment by iCrawl** [comment]
That doesn't look like it failed at the end it does try to compile it.

Can you try upgrading to node 16 or downgrade to 14?

15 is an in between version we usually don't support since it's not an official LTS.

**Comment by stepkrep** [comment]
> That doesn't look like it failed at the end it does try to compile it.
> 
> Can you try upgrading to node 16 or downgrade to 14?
> 
> 15 is an in between version we usually don't support since it's not an official LTS.

I try to put the 14.16.1 and see if it works

**Comment by stepkrep** [comment]
Fixed by downgrading node, thx @iCrawl
