### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by MegaGuicker** [discordjs/opus#84]
When i want to install, i get that : 

node-pre-gyp ERR! install response status 404 Not Found on https://github.com/discordjs/opus/releases/download/v0.5.0/opus-v0.5.0-node-v72-napi-v3-linux-x64-glibc-2.32.tar.gz
node-pre-gyp WARN Pre-built binaries not installable for @discordjs/opus@0.5.0 and node@12.18.2 (node-v72 ABI, glibc) (falling back to source compile with node-gyp)
node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/discordjs/opus/releases/download/v0.5.0/opus-v0.5.0-node-v72-napi-v3-linux-x64-glibc-2.32.tar.gz

I noticed at the end libc version is 32 but it's still 31 in the release?

**Include a reproducible code sample here, if possible:**

npm i @discordjs/opus

- @discordjs/opus version: 0.5.0
- Node.js version: 12.18.2
- Operating system: ubuntu 20.10

**Comment by iCrawl** [comment]
None of those three things are errors. Any more information in the console?

Those 3 lines just indicate that there isn't a prebuilt release and it will attempt to build it on your system.

**Comment by MegaGuicker** [comment]
> @discordjs/opus@0.5.0 install /home/server/lala-bot/node_modules/@discordjs/opus
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! install response status 404 Not Found on https://github.com/discordjs/opus/releases/download/v0.5.0/opus-v0.5.0-node-v72-napi-v3-linux-x64-glibc-2.32.tar.gz
node-pre-gyp WARN Pre-built binaries not installable for @discordjs/opus@0.5.0 and node@12.18.2 (node-v72 ABI, glibc) (falling back to source compile with node-gyp)
node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/discordjs/opus/releases/download/v0.5.0/opus-v0.5.0-node-v72-napi-v3-linux-x64-glibc-2.32.tar.gz
make: Entering directory '/home/server/lala-bot/node_modules/@discordjs/opus/build'
  CC(target) Release/obj.target/libopus/deps/opus/src/opus_multistream.o
  CC(target) Release/obj.target/libopus/deps/opus/src/opus_projection_encoder.o
  CC(target) Release/obj.target/libopus/deps/opus/src/analysis.o
  CC(target) Release/obj.target/libopus/deps/opus/src/mlp_data.o
  CC(target) Release/obj.target/libopus/deps/opus/src/opus_multistream_encoder.o
  CC(target) Release/obj.target/libopus/deps/opus/src/opus_projection_decoder.o
  CC(target) Release/obj.target/libopus/deps/opus/src/mapping_matrix.o
  CC(target) Release/obj.target/libopus/deps/opus/src/opus_compare.o
  CC(target) Release/obj.target/libopus/deps/opus/src/mlp.o
  CC(target) Release/obj.target/libopus/deps/opus/src/opus.o
  CC(target) Release/obj.target/libopus/deps/opus/src/opus_multistream_decoder.o
  CC(target) Release/obj.target/libopus/deps/opus/src/opus_decoder.o
  CC(target) Release/obj.target/libopus/deps/opus/src/repacketizer.o
  CC(target) Release/obj.target/libopus/deps/opus/src/opus_encoder.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/decode_frame.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/float/inner_product_FLP.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/float/scale_vector_FLP.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/float/find_pred_coefs_FLP.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/float/schur_FLP.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/float/warped_autocorrelation_FLP.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/float/burg_modified_FLP.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/float/find_LPC_FLP.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/float/LPC_inv_pred_gain_FLP.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/float/scale_copy_vector_FLP.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/float/noise_shape_analysis_FLP.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/float/pitch_analysis_core_FLP.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/float/bwexpander_FLP.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/float/LTP_analysis_filter_FLP.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/float/LTP_scale_ctrl_FLP.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/float/corrMatrix_FLP.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/float/encode_frame_FLP.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/float/sort_FLP.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/float/find_pitch_lags_FLP.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/float/residual_energy_FLP.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/float/LPC_analysis_filter_FLP.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/float/autocorrelation_FLP.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/float/k2a_FLP.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/float/regularize_correlations_FLP.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/float/find_LTP_FLP.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/float/energy_FLP.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/float/apply_sine_window_FLP.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/float/wrappers_FLP.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/float/process_gains_FLP.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/stereo_quant_pred.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/LPC_inv_pred_gain.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/process_NLSFs.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/NSQ.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/check_control_input.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/NLSF_del_dec_quant.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/LPC_analysis_filter.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/dec_API.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/resampler.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/sort.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/VAD.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/resampler_private_AR2.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/LPC_fit.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/control_SNR.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/decode_parameters.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/pitch_est_tables.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/fixed/warped_autocorrelation_FIX.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/fixed/apply_sine_window_FIX.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/fixed/residual_energy16_FIX.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/fixed/schur64_FIX.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/fixed/residual_energy_FIX.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/fixed/noise_shape_analysis_FIX.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/fixed/encode_frame_FIX.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/fixed/schur_FIX.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/fixed/autocorr_FIX.o
../deps/opus/silk/fixed/autocorr_FIX.c: In function ‘silk_autocorr’:
../deps/opus/silk/fixed/autocorr_FIX.c:47:29: warning: passing argument 1 of ‘_celt_autocorr’ from incompatible pointer type [-Wincompatible-pointer-types]
   47 |     *scale = _celt_autocorr(inputData, results, NULL, 0, corrCount-1, inputDataSize, arch);
      |                             ^~~~~~~~~
      |                             |
      |                             const opus_int16 * {aka const short int *}
In file included from ../deps/opus/silk/fixed/autocorr_FIX.c:33:
../deps/opus/celt/celt_lpc.h:63:38: note: expected ‘const opus_val16 *’ {aka ‘const float *’} but argument is of type ‘const opus_int16 *’ {aka ‘const short int *’}
   63 | int _celt_autocorr(const opus_val16 *x, opus_val32 *ac,
      |                    ~~~~~~~~~~~~~~~~~~^
../deps/opus/silk/fixed/autocorr_FIX.c:47:40: warning: passing argument 2 of ‘_celt_autocorr’ from incompatible pointer type [-Wincompatible-pointer-types]
   47 |     *scale = _celt_autocorr(inputData, results, NULL, 0, corrCount-1, inputDataSize, arch);
      |                                        ^~~~~~~
      |                                        |
      |                                        opus_int32 * {aka int *}
In file included from ../deps/opus/silk/fixed/autocorr_FIX.c:33:
../deps/opus/celt/celt_lpc.h:63:53: note: expected ‘opus_val32 *’ {aka ‘float *’} but argument is of type ‘opus_int32 *’ {aka ‘int *’}
   63 | int _celt_autocorr(const opus_val16 *x, opus_val32 *ac,
      |                                         ~~~~~~~~~~~~^~
  CC(target) Release/obj.target/libopus/deps/opus/silk/fixed/burg_modified_FIX.o
../deps/opus/silk/fixed/burg_modified_FIX.c: In function ‘silk_burg_modified_c’:
../deps/opus/silk/fixed/burg_modified_FIX.c:98:30: warning: passing argument 1 of ‘celt_pitch_xcorr_c’ from incompatible pointer type [-Wincompatible-pointer-types]
   98 |             celt_pitch_xcorr(x_ptr, x_ptr + 1, xcorr, subfr_length - D, D, arch );
      |                              ^~~~~
      |                              |
      |                              const opus_int16 * {aka const short int *}
In file included from ../deps/opus/silk/fixed/burg_modified_FIX.c:35:
../deps/opus/celt/pitch.h:185:38: note: expected ‘const opus_val16 *’ {aka ‘const float *’} but argument is of type ‘const opus_int16 *’ {aka ‘const short int *’}
  185 | celt_pitch_xcorr_c(const opus_val16 *_x, const opus_val16 *_y,
      |                    ~~~~~~~~~~~~~~~~~~^~
../deps/opus/silk/fixed/burg_modified_FIX.c:98:43: warning: passing argument 2 of ‘celt_pitch_xcorr_c’ from incompatible pointer type [-Wincompatible-pointer-types]
   98 |             celt_pitch_xcorr(x_ptr, x_ptr + 1, xcorr, subfr_length - D, D, arch );
      |                                     ~~~~~~^~~
      |                                           |
      |                                           const opus_int16 * {aka const short int *}
In file included from ../deps/opus/silk/fixed/burg_modified_FIX.c:35:
../deps/opus/celt/pitch.h:185:60: note: expected ‘const opus_val16 *’ {aka ‘const float *’} but argument is of type ‘const opus_int16 *’ {aka ‘const short int *’}
  185 | celt_pitch_xcorr_c(const opus_val16 *_x, const opus_val16 *_y,
      |                                          ~~~~~~~~~~~~~~~~~~^~
../deps/opus/silk/fixed/burg_modified_FIX.c:98:48: warning: passing argument 3 of ‘celt_pitch_xcorr_c’ from incompatible pointer type [-Wincompatible-pointer-types]
   98 |             celt_pitch_xcorr(x_ptr, x_ptr + 1, xcorr, subfr_length - D, D, arch );
      |                                                ^~~~~
      |                                                |
      |                                                opus_int32 * {aka int *}
In file included from ../deps/opus/silk/fixed/burg_modified_FIX.c:35:
../deps/opus/celt/pitch.h:186:19: note: expected ‘opus_val32 *’ {aka ‘float *’} but argument is of type ‘opus_int32 *’ {aka ‘int *’}
  186 |       opus_val32 *xcorr, int len, int max_pitch, int arch);
      |       ~~~~~~~~~~~~^~~~~
  CC(target) Release/obj.target/libopus/deps/opus/silk/fixed/pitch_analysis_core_FIX.o
../deps/opus/silk/fixed/pitch_analysis_core_FIX.c: In function ‘silk_pitch_analysis_core’:
../deps/opus/silk/fixed/pitch_analysis_core_FIX.c:200:27: warning: passing argument 1 of ‘celt_pitch_xcorr_c’ from incompatible pointer type [-Wincompatible-pointer-types]
  200 |         celt_pitch_xcorr( target_ptr, target_ptr - MAX_LAG_4KHZ, xcorr32, SF_LENGTH_8KHZ, MAX_LAG_4KHZ - MIN_LAG_4KHZ + 1, arch );
      |                           ^~~~~~~~~~
      |                           |
      |                           const opus_int16 * {aka const short int *}
In file included from ../deps/opus/silk/fixed/pitch_analysis_core_FIX.c:39:
../deps/opus/celt/pitch.h:185:38: note: expected ‘const opus_val16 *’ {aka ‘const float *’} but argument is of type ‘const opus_int16 *’ {aka ‘const short int *’}
  185 | celt_pitch_xcorr_c(const opus_val16 *_x, const opus_val16 *_y,
      |                    ~~~~~~~~~~~~~~~~~~^~
../deps/opus/silk/fixed/pitch_analysis_core_FIX.c:200:50: warning: passing argument 2 of ‘celt_pitch_xcorr_c’ from incompatible pointer type [-Wincompatible-pointer-types]
  200 |         celt_pitch_xcorr( target_ptr, target_ptr - MAX_LAG_4KHZ, xcorr32, SF_LENGTH_8KHZ, MAX_LAG_4KHZ - MIN_LAG_4KHZ + 1, arch );
      |                                                  ^
      |                                                  |
      |                                                  const opus_int16 * {aka const short int *}
In file included from ../deps/opus/silk/fixed/pitch_analysis_core_FIX.c:39:
../deps/opus/celt/pitch.h:185:60: note: expected ‘const opus_val16 *’ {aka ‘const float *’} but argument is of type ‘const opus_int16 *’ {aka ‘const short int *’}
  185 | celt_pitch_xcorr_c(const opus_val16 *_x, const opus_val16 *_y,
      |                                          ~~~~~~~~~~~~~~~~~~^~
../deps/opus/silk/fixed/pitch_analysis_core_FIX.c:200:66: warning: passing argument 3 of ‘celt_pitch_xcorr_c’ from incompatible pointer type [-Wincompatible-pointer-types]
  200 |         celt_pitch_xcorr( target_ptr, target_ptr - MAX_LAG_4KHZ, xcorr32, SF_LENGTH_8KHZ, MAX_LAG_4KHZ - MIN_LAG_4KHZ + 1, arch );
      |                                                                  ^~~~~~~
      |                                                                  |
      |                                                                  opus_int32 * {aka int *}
In file included from ../deps/opus/silk/fixed/pitch_analysis_core_FIX.c:39:
../deps/opus/celt/pitch.h:186:19: note: expected ‘opus_val32 *’ {aka ‘float *’} but argument is of type ‘opus_int32 *’ {aka ‘int *’}
  186 |       opus_val32 *xcorr, int len, int max_pitch, int arch);
      |       ~~~~~~~~~~~~^~~~~
../deps/opus/silk/fixed/pitch_analysis_core_FIX.c: In function ‘silk_P_Ana_calc_corr_st3’:
../deps/opus/silk/fixed/pitch_analysis_core_FIX.c:616:27: warning: passing argument 1 of ‘celt_pitch_xcorr_c’ from incompatible pointer type [-Wincompatible-pointer-types]
  616 |         celt_pitch_xcorr( target_ptr, target_ptr - start_lag - lag_high, xcorr32, sf_length, lag_high - lag_low + 1, arch );
      |                           ^~~~~~~~~~
      |                           |
      |                           const opus_int16 * {aka const short int *}
In file included from ../deps/opus/silk/fixed/pitch_analysis_core_FIX.c:39:
../deps/opus/celt/pitch.h:185:38: note: expected ‘const opus_val16 *’ {aka ‘const float *’} but argument is of type ‘const opus_int16 *’ {aka ‘const short int *’}
  185 | celt_pitch_xcorr_c(const opus_val16 *_x, const opus_val16 *_y,
      |                    ~~~~~~~~~~~~~~~~~~^~
../deps/opus/silk/fixed/pitch_analysis_core_FIX.c:616:62: warning: passing argument 2 of ‘celt_pitch_xcorr_c’ from incompatible pointer type [-Wincompatible-pointer-types]
  616 |         celt_pitch_xcorr( target_ptr, target_ptr - start_lag - lag_high, xcorr32, sf_length, lag_high - lag_low + 1, arch );
      |                                       ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~
      |                                                              |
      |                                                              const opus_int16 * {aka const short int *}
In file included from ../deps/opus/silk/fixed/pitch_analysis_core_FIX.c:39:
../deps/opus/celt/pitch.h:185:60: note: expected ‘const opus_val16 *’ {aka ‘const float *’} but argument is of type ‘const opus_int16 *’ {aka ‘const short int *’}
  185 | celt_pitch_xcorr_c(const opus_val16 *_x, const opus_val16 *_y,
      |                                          ~~~~~~~~~~~~~~~~~~^~
../deps/opus/silk/fixed/pitch_analysis_core_FIX.c:616:74: warning: passing argument 3 of ‘celt_pitch_xcorr_c’ from incompatible pointer type [-Wincompatible-pointer-types]
  616 |         celt_pitch_xcorr( target_ptr, target_ptr - start_lag - lag_high, xcorr32, sf_length, lag_high - lag_low + 1, arch );
      |                                                                          ^~~~~~~
      |                                                                          |
      |                                                                          opus_int32 * {aka int *}
In file included from ../deps/opus/silk/fixed/pitch_analysis_core_FIX.c:39:
../deps/opus/celt/pitch.h:186:19: note: expected ‘opus_val32 *’ {aka ‘float *’} but argument is of type ‘opus_int32 *’ {aka ‘int *’}
  186 |       opus_val32 *xcorr, int len, int max_pitch, int arch);
      |       ~~~~~~~~~~~~^~~~~
  CC(target) Release/obj.target/libopus/deps/opus/silk/fixed/find_LTP_FIX.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/fixed/find_LPC_FIX.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/fixed/corrMatrix_FIX.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/fixed/k2a_FIX.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/fixed/LTP_scale_ctrl_FIX.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/fixed/process_gains_FIX.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/fixed/k2a_Q16_FIX.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/fixed/regularize_correlations_FIX.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/fixed/LTP_analysis_filter_FIX.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/fixed/vector_ops_FIX.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/fixed/find_pitch_lags_FIX.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/fixed/find_pred_coefs_FIX.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/control_audio_bandwidth.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/decoder_set_fs.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/NLSF_unpack.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/bwexpander.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/resampler_rom.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/shell_coder.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/decode_pulses.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/bwexpander_32.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/decode_core.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/PLC.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/tables_NLSF_CB_WB.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/table_LSF_cos.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/tables_pulses_per_block.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/tables_gain.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/inner_prod_aligned.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/resampler_down2_3.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/NSQ_del_dec.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/decode_pitch.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/NLSF_VQ_weights_laroia.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/interpolate.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/debug.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/tables_other.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/LP_variable_cutoff.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/NLSF_decode.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/encode_pulses.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/control_codec.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/stereo_LR_to_MS.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/HP_variable_cutoff.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/encode_indices.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/init_decoder.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/stereo_encode_pred.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/NLSF_VQ.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/init_encoder.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/resampler_private_IIR_FIR.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/resampler_private_up2_HQ.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/sigm_Q15.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/sum_sqr_shift.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/tables_LTP.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/resampler_down2.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/code_signs.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/tables_NLSF_CB_NB_MB.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/gain_quant.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/tables_pitch_lag.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/NLSF_stabilize.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/stereo_find_predictor.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/A2NLSF.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/NLSF2A.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/VQ_WMat_EC.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/NLSF_encode.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/log2lin.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/stereo_decode_pred.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/lin2log.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/CNG.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/enc_API.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/biquad_alt.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/quant_LTP_gains.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/resampler_private_down_FIR.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/ana_filt_bank_1.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/stereo_MS_to_LR.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/decode_indices.o
  CC(target) Release/obj.target/libopus/deps/opus/celt/rate.o
  CC(target) Release/obj.target/libopus/deps/opus/celt/entdec.o
  CC(target) Release/obj.target/libopus/deps/opus/celt/modes.o
  CC(target) Release/obj.target/libopus/deps/opus/celt/celt_lpc.o
  CC(target) Release/obj.target/libopus/deps/opus/celt/laplace.o
  CC(target) Release/obj.target/libopus/deps/opus/celt/cwrs.o
  CC(target) Release/obj.target/libopus/deps/opus/celt/celt.o
  CC(target) Release/obj.target/libopus/deps/opus/celt/entcode.o
  CC(target) Release/obj.target/libopus/deps/opus/celt/celt_decoder.o
  CC(target) Release/obj.target/libopus/deps/opus/celt/celt_encoder.o
  CC(target) Release/obj.target/libopus/deps/opus/celt/mdct.o
  CC(target) Release/obj.target/libopus/deps/opus/celt/quant_bands.o
  CC(target) Release/obj.target/libopus/deps/opus/celt/vq.o
  CC(target) Release/obj.target/libopus/deps/opus/celt/bands.o
  CC(target) Release/obj.target/libopus/deps/opus/celt/kiss_fft.o
  CC(target) Release/obj.target/libopus/deps/opus/celt/entenc.o
  CC(target) Release/obj.target/libopus/deps/opus/celt/mathops.o
  CC(target) Release/obj.target/libopus/deps/opus/celt/pitch.o
  AR(target) Release/obj.target/deps/opus.a
  COPY Release/opus.a
  CXX(target) Release/obj.target/opus/src/node-opus.o
<command-line>: warning: ISO C++11 requires whitespace after the macro name
../src/node-opus.cc: In member function ‘Napi::Value OpusEncoder::Encode(const Napi::CallbackInfo&)’:
../src/node-opus.cc:103:1: warning: control reaches end of non-void function [-Wreturn-type]
  103 | }
      | ^
../src/node-opus.cc: In member function ‘Napi::Value OpusEncoder::Decode(const Napi::CallbackInfo&)’:
../src/node-opus.cc:134:1: warning: control reaches end of non-void function [-Wreturn-type]
  134 | }
      | ^
  SOLINK_MODULE(target) /home/server/lala-bot/node_modules/@discordjs/opus/prebuild/node-v72-napi-v3-linux-x64-glibc-2.32/opus.node
  COPY Release/opus.node
make: Leaving directory '/home/server/lala-bot/node_modules/@discordjs/opus/build'
npm WARN lala-bot@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ @discordjs/opus@0.5.0
updated 1 package and audited 227 packages in 25.275s

9 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

**Comment by MegaGuicker** [comment]
When i perform a node >require("@discordjs/opus"); it output that : 
Uncaught:
Error: Cannot find module '/home/server/lala-bot/node_modules/@discordjs/opus/prebuild/node-v83-napi-v3-linux-x64-glibc-2.32/opus.node'
Require stack:
- /home/server/lala-bot/node_modules/@discordjs/opus/lib/index.js
- <repl>
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/server/lala-bot/node_modules/@discordjs/opus/lib/index.js',
    '<repl>'
  ]
}
but in my folder i have that : node_modules/@discordjs/opus/prebuild/node-v72-napi-v3-linux-x64-glibc-2.32
so he search for the wrong one.

**Comment by iCrawl** [comment]
That looks to me like conflicting node versions, so not really a problem with this library since it builds and installs just fine.

**Comment by MegaGuicker** [comment]
I'l try changing node version

**Comment by MegaGuicker** [comment]
it's seems to be the solution.
