### ISSUE TITLE
Tries to install v93 even though there is no v93 release available

### ISSUE THREAD

**Issue by DennisRein** [discordjs/opus#86]
**Please describe the problem you are having in as much detail as possible:**
Tries to install v93 even though there is no v93 release available, am I able to pass a flag somehow to choose v88?

**Include a reproducible code sample here, if possible:**

```js
npm install discord.js @discordjs/opus
```
**Further details:**

node-pre-gyp http GET https://github.com/discordjs/opus/releases/download/v0.5.0/opus-v0.5.0-node-v93-napi-v3-win32-x64-
npm ERR! node-pre-gyp ERR! install response status 404 Not Found on https://github.com/discordjs/opus/releases/download/v0.5.0/opus-v0.5.0-node-v93-napi-v3-win32-x64-unknown-unknown.tar.gz
npm ERR! node-pre-gyp WARN Pre-built binaries not installable for @discordjs/opus@0.5.0 and node@16.0.0 (node-v93 ABI, unknown) (falling back to source compile with node-gyp)
npm ERR! node-pre-gyp WARN Hit error response status 404 Not Fou
unknown-unknown.tar.gz

- @discordjs/opus version:
- Node.js version: v16.0.0
- Operating system: Windows 10
- Priority this issue should have – please be realistic and elaborate if possible: Medium

**Comment by DennisRein** [comment]
Fixed by deleting the @discordjs folder in the modules folder and running 
npm i @discordjs/node-pre-gyp node-addon-api @discordjs/opus

**Comment by iCrawl** [comment]
Yeah thats not the libs fault.
