### ISSUE TITLE
Support for nodejs 16

### ISSUE THREAD

**Issue by Dev-CasperTheGhost** [discordjs/opus#89]
**Is your feature request related to a problem? Please describe.**

Not really. Would be nice to install @discordjs/opus on node 16. 

**Describe the ideal solution**

Able to install @discordjs/opus with nodejs version 16

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by iCrawl** [comment]
Can you elaborate how Node 16 is not supported currently?

**Comment by Dev-CasperTheGhost** [comment]
Oh. After checking the error again it looks like it's [something with erlpack](https://paste.caspertheghost.me/pastes/298113119796855301)?

**Comment by iCrawl** [comment]
Yup, nothing to do with this library.

**Comment by Dev-CasperTheGhost** [comment]
alright thanks, sorry for the inconvenience.
