### ISSUE TITLE
armhf (raspi 4) support

### ISSUE THREAD

**Issue by Zigecek** [discordjs/opus#92]
Hi, I have a long trouble with installing @discordjs/opus on my raspberry. Every time I'm installing it, it has to compile it, but while compiling there are some "hidden" errors, bcs after installation, it is not working properly (i.e. `dispatcher.resume()` doesn't work). Sometimes I get to install it working.

On windows 10, there is no compiling needed, bcs it is already pre-builded, so my solution is to pre-build it for armhf architecture.

Otherwise if you can't pre-build it, can I somehow build it on my computer and then use it on raspberry?

**Comment by iCrawl** [comment]
`dispatcher.resume()` has nothing to do with this library.

**Comment by Zigecek** [comment]
> `dispatcher.resume()` has nothing to do with this library.

Idk, but it is not working due the compiling. I just don't know how can I get it to work everytime...

**Comment by iCrawl** [comment]
Again, this library has nothing to do with the methods you use. If it compiles, it is working.

If it would not play music at all and crash, then I could maybe see how its related to this library.

**Comment by iCrawl** [comment]
You issue might be related to this at most: https://github.com/discordjs/discord.js/issues/5300

**Comment by Zigecek** [comment]
> You issue might be related to this at most: [discordjs/discord.js#5300](https://github.com/discordjs/discord.js/issues/5300)

I will try, thx,
