### ISSUE TITLE
You didn't update it to support macOS ARM64, instead you deleted a header file, from what I see.

### ISSUE THREAD

**Issue by StupidRepo** [discordjs/opus#98]
**Please describe the problem you are having in as much detail as possible:**

I literally cannot `npm i @discordjs/opus`. It gives me a missing header error.

I am on an M1 MacBook Pro.

**Include a reproducible code sample here, if possible:**

```js
// Place your code here
```

**Further details:**
```
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! In file included from ../deps/opus/src/opus_decoder.c:50:
npm ERR! In file included from ../deps/opus/silk/structs.h:32:
npm ERR! In file included from ../deps/opus/silk/SigProc_FIX.h:51:
npm ERR! ../deps/opus/silk/arm/biquad_alt_arm.h:31:11: fatal error: 'celt/arm/armcpu.h' file not found
npm ERR! # include "celt/arm/armcpu.h"
npm ERR!           ^~~~~~~~~~~~~~~~~~~
npm ERR! 1 error generated.
npm ERR! make: *** [Release/obj.target/libopus/deps/opus/src/opus_decoder.o] Error 1
```
- @discordjs/opus version: none lol
- Node.js version: 16.6.2
- Operating system: macOS 11 - ARM
- Priority this issue should have – please be realistic and elaborate if possible: SUPER HIGH! (For the Mac Users)

**Comment by kyranet** [comment]
cc: @Androz2091

**Comment by StupidRepo** [comment]
What do you mean by "cc: @Androz2091"?

**Comment by Androz2091** [comment]
I am using a Mac Mini m1. It worked when creating an empty project and using npm install. I can try again by clearing the cache maybe? If you have any other idea please let me know

**Comment by kyranet** [comment]
"cc" means [Carbon Copy](https://en.wikipedia.org/wiki/Carbon_copy), the same as e-mails, and is used in GitHub to bring somebody's attention.

The PR #97 is what made this change in MacOS ARM64 compatibility, so I just mentioned the author. I hope that helps understanding that @StupidRepo

**Comment by StupidRepo** [comment]
Ah ok

**Comment by StupidRepo** [comment]
So do we have a general idea why this isn't working?

**Comment by Keke27210** [comment]
There is no issue with the code, it's just that the fix hasn't been released yet. `@discordjs/opus` on npm does not include #97, so wait for the next release or install it from this repository `npm i discordjs/opus`.

**Comment by kyranet** [comment]
https://github.com/discordjs/opus/releases/tag/v0.6.0 has been released, please update at your earliest convenience 👍🏼

**Comment by StupidRepo** [comment]
Thanks! Will update now

**Comment by StupidRepo** [comment]
Holy crap thank you so much!
